using System;
using System.Linq;
using System.Threading.Tasks;
using CTXD.Client.Features.Battle;
using CTXD.Client.Features.FirstPlayable;
using CTXD.Client.Networking;
using UnityEngine;
using UnityEngine.UI;

namespace CTXD.Client.Features.World
{
    public sealed class MinePanel:MonoBehaviour
    {
        static MinePanel _open;ApiClient _api;Action<string> _status;RectTransform _window;MineView _view;GeneralRosterResponse _roster;int _style=1,_page=1,_generalId;bool _busy;
        public static MinePanel Open(RectTransform host,ApiClient api,Action<string> status,int generalId=0){if(_open!=null)Destroy(_open.gameObject);var go=new GameObject("MinePanel");go.transform.SetParent(host,false);var p=go.AddComponent<MinePanel>();p._api=api;p._status=status;p._generalId=generalId;_open=p;p.Build();_=p.Load();return p;}
        public static void RefreshOpenFromPush(){if(_open!=null&&!_open._busy)_=_open.Load();}void OnDestroy(){if(_open==this)_open=null;}
        void Build(){var b=LegacyUiFactory.Panel(transform,"MineBlocker",Vector2.zero,Vector2.one,new Color(0,0,0,.75f));_window=LegacyUiFactory.PixelPanel(b,"MineWindow",250,65,780,610,new Color(.045f,.036f,.025f,.99f));LegacyUiFactory.PixelLabel(_window,"KHOÁNG TRƯỜNG",22,TextAnchor.MiddleCenter,new Color(1,.82f,.35f),210,12,360,35);}
        async Task Load(){if(_busy)return;_busy=true;try{_view=await _api.GetMinesAsync(_page,_style);_page=_view.currentPage;_roster=await _api.GetGeneralsAsync();var ready=(_roster?.military??Array.Empty<GeneralView>()).FirstOrDefault(x=>x.state<=1&&x.forces>0);if(_generalId==0&&ready!=null)_generalId=ready.id;Draw();}catch(Exception e){_status(e.Message);}finally{_busy=false;}}
        void Draw(){if(_view==null)return;LegacyUiFactory.DestroyChildren(_window);LegacyUiFactory.PixelLabel(_window,"KHOÁNG TRƯỜNG",22,TextAnchor.MiddleCenter,new Color(1,.82f,.35f),210,10,360,35);LegacyUiFactory.PixelButton(_window,"Đóng",695,14,65,27,()=>Destroy(gameObject));LegacyUiFactory.PixelButton(_window,(_style==1?"▶ ":"")+"Thiết khoáng",20,55,170,32,()=>Switch(1));LegacyUiFactory.PixelButton(_window,(_style==2?"▶ ":"")+"Bảo thạch",200,55,170,32,()=>Switch(2));LegacyUiFactory.PixelButton(_window,"‹",390,55,45,32,()=>Page(-1));LegacyUiFactory.PixelLabel(_window,$"Trang {_view.currentPage}/{_view.totalPage}",15,TextAnchor.MiddleCenter,Color.white,440,55,120,32);LegacyUiFactory.PixelButton(_window,"›",565,55,45,32,()=>Page(1));LegacyUiFactory.PixelButton(_window,"Làm mới",620,55,140,32,async()=>await Load());var generals=_roster?.military??Array.Empty<GeneralView>();var selected=generals.FirstOrDefault(x=>x.id==_generalId);LegacyUiFactory.PixelLabel(_window,"Tướng: "+(selected?.name??"chưa chọn"),15,TextAnchor.MiddleLeft,new Color(.9f,.86f,.75f),20,94,250,27);for(var i=0;i<Math.Min(3,generals.Length);i++){var g=generals[i];LegacyUiFactory.PixelButton(_window,(g.id==_generalId?"▶ ":"")+g.name,280+i*158,94,150,27,()=>{_generalId=g.id;Draw();});}var slots=(_view.mines??Array.Empty<MineSlotView>()).Where(x=>x.type==(_style==1?2:4)).Take(12).ToArray();for(var i=0;i<slots.Length;i++){var m=slots[i];var col=i%2;var row=i/2;var x=20+col*375;var y=132+row*68;var owner=m.myself?"Của bạn":m.ownerPlayerId>0?(m.ownerName??("#"+m.ownerPlayerId)):"Trống";var extra=m.myself?$" · đã có {m.currentOutput:N0}":"";LegacyUiFactory.PixelLabel(_window,$"#{m.id} {m.name}\nSL {m.output:N0}/giờ · {owner}{extra}",14,TextAnchor.UpperLeft,Color.white,x,y,260,58);LegacyUiFactory.PixelButton(_window,ActionLabel(m),x+265,y+8,98,34,async()=>await Act(m));}var force=(_view.mines??Array.Empty<MineSlotView>()).FirstOrDefault(x=>x.type==(_style==1?1:3));if(force!=null){var nation=force.ownerForceId>0?"Quốc gia "+force.ownerForceId:"Chưa chiếm";LegacyUiFactory.PixelLabel(_window,$"Thế lực khoáng #{force.id} · {nation} · thưởng {force.output:N0}/ngày",15,TextAnchor.MiddleLeft,new Color(1,.82f,.35f),20,548,555,34);LegacyUiFactory.PixelButton(_window,force.operation=="mine"?"Thu hoạch":"Chiếm",590,548,170,34,async()=>await Act(force));}}
        string ActionLabel(MineSlotView m){if(m.operation=="rush")return"Tăng tốc";if(m.operation=="abandon")return m.canDo?"Từ bỏ":"Chờ 15p";if(m.operation=="mine")return m.canDo?"Thu hoạch":"Đã nhận";return m.operation=="rob"?"Tranh đoạt":"Chiếm";}
        async Task Act(MineSlotView m){if(_busy||!m.canDo)return;_busy=true;try{if(m.operation=="rush"){await _api.RushMineAsync(_style);_status("Sản lượng Khoáng Trường từ thời điểm này đã x2.");}else if(m.operation=="abandon"){var r=await _api.AbandonMineAsync(_style);_status($"Đã thu {r.output:N0} sản lượng.");}else if(m.operation=="mine"){var r=await _api.HarvestForceMineAsync(_style);_status($"Đã thu {r.output:N0} từ thế lực khoáng.");}else{if(_generalId==0)throw new Exception("Chọn một võ tướng sẵn sàng.");var r=await _api.OccupyMineAsync(m.id,_generalId);if(r.battleId>0)BattlePanel.Open((RectTransform)_window.parent,_api,_status,r.battleId);else _status("Đã chiếm Khoáng Trường trống.");}}catch(Exception e){_status(e.Message);}finally{_busy=false;}await Load();}
        void Switch(int style){_style=style;_page=1;_=Load();}void Page(int delta){_page=Math.Max(1,Math.Min(_view.totalPage,_page+delta));_=Load();}
    }
}
