using CTXD.Server.Data;using Npgsql;
namespace CTXD.Server.Services;
public sealed record ActivityScheduleRequest(int ActivityType,DateTimeOffset StartAt,DateTimeOffset EndAt,string ParamsInfo);
public sealed record ActivityScheduleView(long Id,int ActivityType,DateTimeOffset StartAt,DateTimeOffset EndAt,string ParamsInfo,int Status);
public sealed class ActivityScheduleService(GameDb db,GamePushHub push,IronActivityService iron,DragonActivityService dragon,SlaveActivityService slave)
{
 public async Task<ActivityScheduleView> ProvisionAsync(ActivityScheduleRequest request,CancellationToken ct){Validate(request);await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using(var active=new NpgsqlCommand("SELECT 1 FROM scheduled_activities WHERE activity_type=$1 AND status<2 FOR UPDATE",c,t)){active.Parameters.AddWithValue(request.ActivityType);if(await active.ExecuteScalarAsync(ct)is not null)throw new GameException("ACTIVITY_ALREADY_SCHEDULED","Legacy activity type already has an open schedule.",409);}long id;await using(var add=new NpgsqlCommand("INSERT INTO scheduled_activities(activity_type,start_at,end_at,params_info,status) VALUES($1,$2,$3,$4,CASE WHEN $2<=now() THEN 1 ELSE 0 END) RETURNING id",c,t)){add.Parameters.AddWithValue(request.ActivityType);add.Parameters.AddWithValue(request.StartAt);add.Parameters.AddWithValue(request.EndAt);add.Parameters.AddWithValue(request.ParamsInfo??"");id=Convert.ToInt64(await add.ExecuteScalarAsync(ct));}await t.CommitAsync(ct);var view=new ActivityScheduleView(id,request.ActivityType,request.StartAt,request.EndAt,request.ParamsInfo??"",request.StartAt<=DateTimeOffset.UtcNow?1:0);if(view.Status==1)await push.BroadcastAsync("activity.updated",new{kind="started",view.Id,view.ActivityType,view.EndAt},ct);return view;}
 public async Task<ActivityScheduleView[]> ListAsync(CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);var rows=new List<ActivityScheduleView>();await using var q=new NpgsqlCommand("SELECT id,activity_type,start_at,end_at,params_info,status FROM scheduled_activities ORDER BY start_at DESC",c);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetInt32(1),r.GetFieldValue<DateTimeOffset>(2),r.GetFieldValue<DateTimeOffset>(3),r.GetString(4),r.GetInt16(5)));return rows.ToArray();}
 public async Task TickAsync(CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);var changed=new List<(long id,int type,int status,DateTimeOffset end)>();await using(var q=new NpgsqlCommand("UPDATE scheduled_activities SET status=1,activated_at=now() WHERE status=0 AND start_at<=now() AND end_at>now() RETURNING id,activity_type,status,end_at",c)){await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))changed.Add((r.GetInt64(0),r.GetInt32(1),r.GetInt16(2),r.GetFieldValue<DateTimeOffset>(3)));}await using(var q=new NpgsqlCommand("UPDATE scheduled_activities SET status=2,expired_at=now() WHERE status<2 AND end_at<=now() RETURNING id,activity_type,status,end_at",c)){await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))changed.Add((r.GetInt64(0),r.GetInt32(1),r.GetInt16(2),r.GetFieldValue<DateTimeOffset>(3)));}foreach(var x in changed){if(x.status==2&&x.type==4)await dragon.FinalizeAsync(x.id,ct);if(x.status==2&&x.type==5)await iron.FinalizeAsync(x.id,ct);if(x.status==2&&x.type==9)await slave.FinalizeAsync(x.id,ct);await push.BroadcastAsync("activity.updated",new{kind=x.status==1?"started":"ended",id=x.id,activityType=x.type,endAt=x.end},ct);}}
 static void Validate(ActivityScheduleRequest r){if(r.ActivityType is<1 or>9)throw new GameException("ACTIVITY_TYPE_INVALID","Legacy activity type must be 1-9.");if(r.StartAt>=r.EndAt||r.EndAt<=DateTimeOffset.UtcNow)throw new GameException("ACTIVITY_TIME_INVALID","Activity time range is invalid.");if(r.StartAt>DateTimeOffset.UtcNow&&r.StartAt<DateTimeOffset.UtcNow.AddMinutes(1))throw new GameException("ACTIVITY_START_TOO_SOON","Legacy schedule requires at least one minute before start.");var raw=r.ParamsInfo??"";if(r.ActivityType==3)Pairs(raw,2,true);if(r.ActivityType==5)ValidateIron(raw);if(r.ActivityType==8)ValidateDstq(raw);}
 static void Pairs(string raw,int size,bool floating){var rows=raw.Split(';',StringSplitOptions.RemoveEmptyEntries);if(rows.Length==0||rows.Any(x=>x.Split(',').Length!=size))throw new GameException("ACTIVITY_PARAMS_INVALID","Legacy activity params are invalid.");foreach(var v in rows.SelectMany(x=>x.Split(',')))if(floating?!double.TryParse(v,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out _):!int.TryParse(v,out _))throw new GameException("ACTIVITY_PARAMS_INVALID","Legacy activity params are invalid.");}
 static void ValidateIron(string raw){Pairs(raw,2,false);var maxNeed=0;var maxReward=0;foreach(var row in raw.Split(';',StringSplitOptions.RemoveEmptyEntries)){var v=row.Split(',').Select(int.Parse).ToArray();if(v[0]<=maxNeed||v[1]<=maxReward||v[0]<=0||v[1]/(double)v[0]>.5)throw new GameException("ACTIVITY_PARAMS_INVALID","Iron thresholds violate the legacy ordering or 50% protection rule.");maxNeed=v[0];maxReward=v[1];}}
 static void ValidateDstq(string raw){Pairs(raw,3,false);var maxNeed=0;var maxReward=0;var maxType=0;foreach(var row in raw.Split(';',StringSplitOptions.RemoveEmptyEntries)){var v=row.Split(',').Select(int.Parse).ToArray();if(v[0]<=maxNeed||v[1]<maxReward||v[2] is not(1 or 2)||v[2]<maxType||v[0]<=0||v[1]/(double)v[0]>.3)throw new GameException("ACTIVITY_PARAMS_INVALID","DSTQ thresholds violate the legacy ordering or 30% protection rule.");maxNeed=v[0];maxReward=v[1];maxType=v[2];}}
}
public sealed class ActivityScheduleWorker(ActivityScheduleService schedules,ILogger<ActivityScheduleWorker> log):BackgroundService
{protected override async Task ExecuteAsync(CancellationToken stoppingToken){while(!stoppingToken.IsCancellationRequested){try{await schedules.TickAsync(stoppingToken);}catch(Exception e){log.LogError(e,"Activity scheduler tick failed");}await Task.Delay(TimeSpan.FromSeconds(5),stoppingToken);}}}
