using CTXD.Server.Data;using CTXD.Server.Domain;using Npgsql;
namespace CTXD.Server.Services;
public sealed record OnlineGiftView(int Remaining,int Available,DateTimeOffset NextAt);
public sealed record OnlineGiftClaimRequest(string RequestKey);
public sealed record OnlineGiftReward(int RewardId,int Food,int Remaining,int Available);
public sealed class ActivityGiftService(GameDb db,CanonicalContent content,TechnologyEffectService technologies,GamePushHub push)
{
 public async Task<OnlineGiftView> GetAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);var view=await AccrueAsync(c,t,player,ct);await t.CommitAsync(ct);return view;}
 public async Task<OnlineGiftReward> ClaimAsync(long player,string key,CancellationToken ct){if(string.IsNullOrWhiteSpace(key))throw new GameException("GIFT_REQUEST_INVALID","Gift request key is required.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using(var old=new NpgsqlCommand("SELECT reward_id,food FROM player_online_gift_claims WHERE player_id=$1 AND request_key=$2",c,t)){old.Parameters.AddWithValue(player);old.Parameters.AddWithValue(key);await using var r=await old.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){var rid=r.GetInt32(0);var oldFood=r.GetInt32(1);var state=await AccrueAsync(c,t,player,ct);await t.CommitAsync(ct);return new(rid,oldFood,state.Remaining,state.Available);}}var current=await AccrueAsync(c,t,player,ct);if(current.Available<=0)throw new GameException("ONLINE_GIFT_UNAVAILABLE","No hourly online gift is available.");var reward=Weighted(content.HourlyRewards.ToArray());var tech=await technologies.GetCompletedIntEffectAsync(player,42,0,ct,c,t);var food=(int)(reward.Food*(1+tech/100d));await using(var save=new NpgsqlCommand("UPDATE player_online_gifts SET available=available-1 WHERE player_id=$1;UPDATE player_resources SET food=food+$3 WHERE player_id=$1;INSERT INTO player_online_gift_claims(player_id,request_key,reward_id,food) VALUES($1,$2,$4,$3)",c,t)){save.Parameters.AddWithValue(player);save.Parameters.AddWithValue(key);save.Parameters.AddWithValue(food);save.Parameters.AddWithValue(reward.Id);await save.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);await push.SendAsync(player,"activity.updated",new{kind="onlineGift",reward.Id,food},ct);return new(reward.Id,food,current.Remaining,current.Available-1);}
 async Task<OnlineGiftView> AccrueAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,CancellationToken ct){await using(var gate=new NpgsqlCommand("SELECT 1 FROM player_functions WHERE player_id=$1 AND function_id=39",c,t)){gate.Parameters.AddWithValue(player);if(await gate.ExecuteScalarAsync(ct)is null)throw new GameException("ONLINE_GIFT_LOCKED","Legacy online gift function 39 is not open.",403);}int remaining,available;DateTimeOffset accrued;await using(var q=new NpgsqlCommand("INSERT INTO player_online_gifts(player_id) VALUES($1) ON CONFLICT DO NOTHING;SELECT remaining,available,accrued_at FROM player_online_gifts WHERE player_id=$1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(player);await using var r=await q.ExecuteReaderAsync(ct);await r.NextResultAsync(ct);await r.ReadAsync(ct);remaining=r.GetInt16(0);available=r.GetInt16(1);accrued=r.GetFieldValue<DateTimeOffset>(2);}var hours=Math.Min(remaining,Math.Max(0,(int)((DateTimeOffset.UtcNow-accrued).TotalHours)));if(hours>0){remaining-=hours;available+=hours;accrued=accrued.AddHours(hours);await using var u=new NpgsqlCommand("UPDATE player_online_gifts SET remaining=$2,available=$3,accrued_at=$4 WHERE player_id=$1",c,t);u.Parameters.AddWithValue(player);u.Parameters.AddWithValue((short)remaining);u.Parameters.AddWithValue((short)available);u.Parameters.AddWithValue(accrued);await u.ExecuteNonQueryAsync(ct);}return new(remaining,available,accrued.AddHours(1));}
 static HourlyRewardDefinition Weighted(HourlyRewardDefinition[] rewards){var n=Random.Shared.NextDouble();foreach(var r in rewards){n-=r.Prob;if(n<=0)return r;}return rewards[^1];}
}
