using System.Text.Json;
using CTXD.Server.Data;
using CTXD.Server.Domain;
using CTXD.Server.Models;
using Npgsql;

namespace CTXD.Server.Services;

public sealed class BattleService(GameDb db, CanonicalContent content, WorldService world, TechnologyEffectService technologies, ExperienceService experience, OfficeService offices, NationProgressService nationProgress,BattleExpActivityService battleExpActivity,DstqActivityService dstq,MineService mines,TreasureService treasures)
{
    const int Active = 0, AttackerWon = 1, DefenderWon = 2;

    public async Task<BattleView> GetAsync(long playerId, long battleId, CancellationToken ct)
    {
        await EnsureAsync(playerId, battleId, ct);
        await using var c = await db.DataSource.OpenConnectionAsync(ct);
        await AuthorizeAsync(c, null, playerId, battleId, ct);
        return await ReadAsync(c, null, battleId, ct);
    }

    public async Task<BattleView> AdvanceAsync(long playerId, long battleId, CancellationToken ct)
    {
        await EnsureAsync(playerId, battleId, ct);
        bool? attackerWon = null;
        await using (var c = await db.DataSource.OpenConnectionAsync(ct))
        await using (var t = await c.BeginTransactionAsync(ct))
        {
            await AuthorizeAsync(c, t, playerId, battleId, ct);
            int status, round, city, battleType;long eventNpcId;
            await using (var cmd = new NpgsqlCommand("SELECT b.status,b.round_no,b.city_id,h.battle_type,COALESCE((h.result_payload->>'eventNpcId')::bigint,0) FROM battles b JOIN world_battle_handoffs h ON h.id=b.id WHERE b.id=$1 FOR UPDATE OF b", c, t))
            { cmd.Parameters.AddWithValue(battleId); await using var r = await cmd.ExecuteReaderAsync(ct); await r.ReadAsync(ct); status=r.GetInt16(0); round=r.GetInt32(1); city=r.GetInt32(2); battleType=r.GetInt16(3);eventNpcId=r.GetInt64(4); }
            if (status != Active) { await t.CommitAsync(ct); return await GetAsync(playerId, battleId, ct); }
            var att = await FrontAsync(c, t, battleId, 1, ct); var def = await FrontAsync(c, t, battleId, 2, ct);
            if (att is null || def is null) attackerWon = att is not null;
            else
            {
                var terrain = battleType==4 ? 6 : battleType is 6 or 7 ? 9 : content.WorldCities.TryGetValue(city, out var wc) ? wc.Terrain : 0;
                var tactic = await ApplyTacticsAsync(c,t,battleId,att,def,terrain,ct);
                var strategy = att.SelectedAction==2&&def.SelectedAction==2?ApplyStrategy(att,def):new StrategyDamage(0,0);
                var result = Fight(att, def, terrain);
                if(def.PlayerId.HasValue&&att.PlayerId.HasValue)await nationProgress.RecordPvpDamageAsync(c,t,battleId,round+1,att.PlayerId.Value,result.DefenderDamage+tactic.ToDefender+strategy.ToDefender,ct);
                if(battleType==15&&def.EventNpcId.HasValue&&att.PlayerId.HasValue)await nationProgress.RecordScheduledWorldEventDamageAsync(c,t,battleId,round+1,def.EventNpcId.Value,att.PlayerId.Value,result.DefenderDamage+tactic.ToDefender+strategy.ToDefender,def.Hp<=0,ct);
                if(def.IsNpc&&att.PlayerId.HasValue){if(def.Hp<=0){await nationProgress.RecordTrialKillAsync(c,t,att.PlayerId.Value,city,1,ct);await nationProgress.RecordProtectionKillAsync(c,t,att.PlayerId.Value,city,1,ct);await nationProgress.MarkTaskNpcDefeatedAsync(c,t,att.PlayerId.Value,city,ct);}await nationProgress.RecordTaskDamageAsync(c,t,att.PlayerId.Value,city,result.DefenderDamage+tactic.ToDefender+strategy.ToDefender,def.Hp<=0,ct);}
                await SaveUnitAsync(c, t, att, ct); await SaveUnitAsync(c, t, def, ct);
                await using(var reset=new NpgsqlCommand("UPDATE battle_units SET selected_action=2 WHERE id IN($1,$2) AND hp>0 AND detached=false",c,t)){reset.Parameters.AddWithValue(att.Id);reset.Parameters.AddWithValue(def.Id);await reset.ExecuteNonQueryAsync(ct);}
                await AddRewardsAsync(c,t,battleId,battleType,att,def,result.AttackerDamage+tactic.ToAttacker+strategy.ToAttacker,result.DefenderDamage+tactic.ToDefender+strategy.ToDefender,ct);
                var nextRound = round + 1; var report = JsonSerializer.Serialize(new { result.AttackerTicks, result.DefenderTicks, tactic, strategy });
                await using var save = new NpgsqlCommand(@"INSERT INTO battle_rounds(battle_id,round_no,attacker_unit_id,defender_unit_id,attacker_damage,defender_damage,attacker_hp,defender_hp,winner_side,report)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb); UPDATE battles SET round_no=$2 WHERE id=$1", c, t);
                save.Parameters.AddWithValue(battleId); save.Parameters.AddWithValue(nextRound); save.Parameters.AddWithValue(att.Id); save.Parameters.AddWithValue(def.Id);
                save.Parameters.AddWithValue(result.AttackerDamage); save.Parameters.AddWithValue(result.DefenderDamage); save.Parameters.AddWithValue(att.Hp); save.Parameters.AddWithValue(def.Hp); save.Parameters.AddWithValue(result.WinnerSide); save.Parameters.AddWithValue(report); await save.ExecuteNonQueryAsync(ct);
                await PersistForcesAsync(c, t, att, ct); await PersistForcesAsync(c, t, def, ct);
                var attAlive = await HasAliveAsync(c, t, battleId, 1, ct); var defAlive = await HasAliveAsync(c, t, battleId, 2, ct);
                if (!attAlive || !defAlive) attackerWon = attAlive && !defAlive;
            }
            if (attackerWon.HasValue)
            {
                await using var end = new NpgsqlCommand("UPDATE battles SET status=$2,winner_side=$3,resolved_at=now() WHERE id=$1; UPDATE player_generals g SET state=1,location_id=CASE WHEN $4 IN(3,14) THEN b.city_id ELSE g.location_id END,updated_at=now() FROM battle_units u,battles b WHERE b.id=$1 AND u.battle_id=$1 AND u.player_id=g.player_id AND u.general_id=g.general_id AND u.is_phantom=false", c, t);
                end.Parameters.AddWithValue(battleId); end.Parameters.AddWithValue(attackerWon.Value ? AttackerWon : DefenderWon); end.Parameters.AddWithValue(attackerWon.Value ? 1 : 2); end.Parameters.AddWithValue(battleType); await end.ExecuteNonQueryAsync(ct);
                await using var questWin=new NpgsqlCommand("INSERT INTO player_quest_runtime(player_id,battle_wins) SELECT DISTINCT player_id,1 FROM battle_units WHERE battle_id=$1 AND side=$2 AND player_id IS NOT NULL ON CONFLICT(player_id) DO UPDATE SET battle_wins=player_quest_runtime.battle_wins+1,updated_at=now()",c,t);questWin.Parameters.AddWithValue(battleId);questWin.Parameters.AddWithValue(attackerWon.Value?1:2);await questWin.ExecuteNonQueryAsync(ct);
            }
            await t.CommitAsync(ct);
        }
        if (attackerWon.HasValue)
        {
            int battleType,force,building;long leadPlayer;var winners=new List<long>();await using(var resultConn=await db.DataSource.OpenConnectionAsync(ct)){await using(var meta=new NpgsqlCommand("SELECT battle_type,attacker_force_id,city_id,attacker_player_id FROM world_battle_handoffs WHERE id=$1",resultConn)){meta.Parameters.AddWithValue(battleId);await using var r=await meta.ExecuteReaderAsync(ct);await r.ReadAsync(ct);battleType=r.GetInt16(0);force=r.GetInt16(1);building=r.GetInt32(2);leadPlayer=r.GetInt64(3);}if(battleType==4&&attackerWon.Value){winners.Add(leadPlayer);await using var units=new NpgsqlCommand("SELECT player_id FROM battle_units WHERE battle_id=$1 AND side=1 AND player_id IS NOT NULL AND player_id<>$2 ORDER BY sequence",resultConn);units.Parameters.AddWithValue(battleId);units.Parameters.AddWithValue(leadPlayer);await using var r=await units.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var id=r.GetInt64(0);if(!winners.Contains(id))winners.Add(id);}}}
            if(battleType==4){await using(var resolved=await db.DataSource.OpenConnectionAsync(ct)){await using var cmd=new NpgsqlCommand("UPDATE world_battle_handoffs SET status=$2,resolved_at=now() WHERE id=$1 AND status=0",resolved);cmd.Parameters.AddWithValue(battleId);cmd.Parameters.AddWithValue(attackerWon.Value?1:2);await cmd.ExecuteNonQueryAsync(ct);}if(attackerWon.Value)await offices.ResolveBattleAsync(force,building,winners,ct);}else if(battleType is 6 or 7){await using(var resolved=await db.DataSource.OpenConnectionAsync(ct)){await using var cmd=new NpgsqlCommand("UPDATE world_battle_handoffs SET status=$2,resolved_at=now(),result_payload=result_payload||jsonb_build_object('winnerSide',$3) WHERE id=$1 AND status=0",resolved);cmd.Parameters.AddWithValue(battleId);cmd.Parameters.AddWithValue(attackerWon.Value?1:2);cmd.Parameters.AddWithValue(attackerWon.Value?1:2);await cmd.ExecuteNonQueryAsync(ct);}await mines.ResolveBattleAsync(battleId,attackerWon.Value,ct);}else if(battleType is 16 or 17 or 18){await using var resolved=await db.DataSource.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand("UPDATE world_battle_handoffs SET status=$2,winner_force_id=NULL,resolved_at=now(),result_payload=result_payload||jsonb_build_object('winnerSide',$3) WHERE id=$1 AND status=0",resolved);cmd.Parameters.AddWithValue(battleId);cmd.Parameters.AddWithValue(attackerWon.Value?1:2);cmd.Parameters.AddWithValue(attackerWon.Value?1:2);await cmd.ExecuteNonQueryAsync(ct);}else await world.ResolveBattleAsync(battleId,attackerWon.Value,JsonSerializer.Serialize(new {source="battle.engine"}),ct);
        }
        await using var read = await db.DataSource.OpenConnectionAsync(ct); return await ReadAsync(read, null, battleId, ct);
    }

    public async Task<BattleView> JoinAttackerAsync(long playerId,long battleId,int generalId,CancellationToken ct)
    {
        await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);
        int city,source,status,battleType;
        await using(var cmd=new NpgsqlCommand("SELECT h.city_id,lead.location_id,b.status,h.battle_type FROM world_battle_handoffs h JOIN battles b ON b.id=h.id JOIN players p ON p.id=$2 JOIN player_generals lead ON lead.player_id=h.attacker_player_id AND lead.general_id=h.attacker_general_id WHERE h.id=$1 AND p.force_id=h.attacker_force_id FOR UPDATE OF h,b",c,t)){cmd.Parameters.AddWithValue(battleId);cmd.Parameters.AddWithValue(playerId);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("BATTLE_JOIN_FORBIDDEN","Only the attacking force may reinforce.",403);city=r.GetInt32(0);source=r.GetInt32(1);status=r.GetInt16(2);battleType=r.GetInt16(3);}
        if(status!=Active)throw new GameException("BATTLE_ENDED","Battle has ended.");
        if(battleType==4){await using var count=new NpgsqlCommand("SELECT count(DISTINCT player_id) FROM battle_units WHERE battle_id=$1 AND side=1 AND player_id IS NOT NULL",c,t);count.Parameters.AddWithValue(battleId);if(Convert.ToInt32(await count.ExecuteScalarAsync(ct))>=3)throw new GameException("POSITION_ATTACKER_FULL","Position battle already has three attacking players.");}
        await using(var check=new NpgsqlCommand(battleType==4?"SELECT 1 FROM player_generals WHERE player_id=$1 AND general_id=$2 AND general_type=2 AND state<=1 AND forces>0 FOR UPDATE":"SELECT 1 FROM player_generals WHERE player_id=$1 AND general_id=$2 AND general_type=2 AND state<=1 AND forces>0 AND location_id IN($3,$4) FOR UPDATE",c,t)){check.Parameters.AddWithValue(playerId);check.Parameters.AddWithValue(generalId);if(battleType!=4){check.Parameters.AddWithValue(source);check.Parameters.AddWithValue(city);}if(await check.ExecuteScalarAsync(ct)is null)throw new GameException("BATTLE_JOIN_GENERAL_INVALID","General cannot reinforce this battle.");}
        await using(var duplicate=new NpgsqlCommand("SELECT 1 FROM battle_units WHERE battle_id=$1 AND player_id=$2 AND general_id=$3 AND is_phantom=false",c,t)){duplicate.Parameters.AddWithValue(battleId);duplicate.Parameters.AddWithValue(playerId);duplicate.Parameters.AddWithValue(generalId);if(await duplicate.ExecuteScalarAsync(ct)is not null)throw new GameException("BATTLE_JOIN_DUPLICATE","General already joined.");}
        int sequence;await using(var seq=new NpgsqlCommand("SELECT COALESCE(max(sequence),-1)+1 FROM battle_units WHERE battle_id=$1 AND side=1",c,t)){seq.Parameters.AddWithValue(battleId);sequence=Convert.ToInt32(await seq.ExecuteScalarAsync(ct));}
        await AddPlayerUnitAsync(c,t,battleId,1,sequence,playerId,generalId,city,ct);await using(var stateCmd=new NpgsqlCommand("UPDATE player_generals SET state=3,updated_at=now() WHERE player_id=$1 AND general_id=$2",c,t)){stateCmd.Parameters.AddWithValue(playerId);stateCmd.Parameters.AddWithValue(generalId);await stateCmd.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return await GetAsync(playerId,battleId,ct);
    }

    public async Task<(BattleView battle,int deployed)> JoinTeamAsync(long owner,long battleId,Guid teamId,int expectedCount,int teamBattleType,CancellationToken ct)
    {
        if(teamBattleType is not(0 or 1))throw new GameException("TEAM_BATTLE_TYPE_INVALID","Legacy team battle type must be 0 or 1.");
        await EnsureAsync(owner,battleId,ct);await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);
        int battleType,status,side,city;await using(var meta=new NpgsqlCommand("SELECT h.battle_type,b.status,CASE WHEN EXISTS(SELECT 1 FROM battle_units u WHERE u.battle_id=b.id AND u.player_id=$2 AND u.side=1 AND u.is_phantom=false) THEN 1 WHEN EXISTS(SELECT 1 FROM battle_units u WHERE u.battle_id=b.id AND u.player_id=$2 AND u.side=2 AND u.is_phantom=false) THEN 2 ELSE 0 END,h.city_id FROM world_battle_handoffs h JOIN battles b ON b.id=h.id WHERE h.id=$1 FOR UPDATE OF h,b",c,t)){meta.Parameters.AddWithValue(battleId);meta.Parameters.AddWithValue(owner);await using var r=await meta.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("BATTLE_ENDED","Battle does not exist.",404);battleType=r.GetInt16(0);status=r.GetInt16(1);side=r.GetInt32(2);city=r.GetInt32(3);}
        if(status!=Active)throw new GameException("BATTLE_ENDED","Battle has ended.");if(battleType is not(3 or 14))throw new GameException("TEAM_BATTLE_FORBIDDEN","Legacy teams deploy only into world city battles.");if(side==0)throw new GameException("TEAM_OWNER_NOT_IN_BATTLE","Team owner must already participate in the battle.");
        var members=new List<(long player,int general,int level)>();await using(var q=new NpgsqlCommand("SELECT g.player_id,g.general_id,pg.level FROM social_teams st JOIN social_team_generals g ON g.team_id=st.id JOIN player_generals pg ON pg.player_id=g.player_id AND pg.general_id=g.general_id JOIN players p ON p.id=g.player_id WHERE st.id=$1 AND st.owner_player_id=$2 AND st.expires_at>now() AND p.force_id=st.force_id AND pg.state<=1 AND pg.forces>0 ORDER BY g.joined_at FOR UPDATE OF st,pg",c,t)){q.Parameters.AddWithValue(teamId);q.Parameters.AddWithValue(owner);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))members.Add((r.GetInt64(0),r.GetInt32(1),r.GetInt32(2)));}
        if(members.Count==0)throw new GameException("TEAM_EMPTY","Team has no deployable generals.");if(expectedCount!=members.Count)throw new GameException("TEAM_MEMBER_COUNT_CHANGED","Team membership changed; refresh deploy cost.",409);
        int sequence;await using(var seq=new NpgsqlCommand("SELECT COALESCE(max(sequence),-1)+1 FROM battle_units WHERE battle_id=$1 AND side=$2",c,t)){seq.Parameters.AddWithValue(battleId);seq.Parameters.AddWithValue(side);sequence=Convert.ToInt32(await seq.ExecuteScalarAsync(ct));}
        var deployed=0;foreach(var member in members){await using(var duplicate=new NpgsqlCommand("SELECT 1 FROM battle_units WHERE battle_id=$1 AND player_id=$2 AND general_id=$3 AND is_phantom=false",c,t)){duplicate.Parameters.AddWithValue(battleId);duplicate.Parameters.AddWithValue(member.player);duplicate.Parameters.AddWithValue(member.general);if(await duplicate.ExecuteScalarAsync(ct)is not null)continue;}await AddPlayerUnitAsync(c,t,battleId,side,sequence++,member.player,member.general,city,ct);deployed++;await using var state=new NpgsqlCommand("UPDATE player_generals SET state=3,updated_at=now() WHERE player_id=$1 AND general_id=$2",c,t);state.Parameters.AddWithValue(member.player);state.Parameters.AddWithValue(member.general);await state.ExecuteNonQueryAsync(ct);if(teamBattleType==1&&deployed>1)await ResolveTeamDuelAsync(c,t,battleId,battleType,city,side,member.player,member.general,ct);}
        var gold=members.Count*3;int free;await using(var token=new NpgsqlCommand("SELECT team_times FROM players WHERE id=$1 FOR UPDATE",c,t)){token.Parameters.AddWithValue(owner);free=Convert.ToInt32(await token.ExecuteScalarAsync(ct));}if(free>0){await using var use=new NpgsqlCommand("UPDATE players SET team_times=team_times-1 WHERE id=$1",c,t);use.Parameters.AddWithValue(owner);await use.ExecuteNonQueryAsync(ct);}else{await using var pay=new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold-$2 WHERE id=$1 AND sys_gold>=$2",c,t);pay.Parameters.AddWithValue(owner);pay.Parameters.AddWithValue(gold);if(await pay.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_GOLD_NOT_ENOUGH","Not enough gold to deploy this team.");await dstq.RecordGoldSpendAsync(c,t,owner,gold,ct);}
        int ownerLevel;await using(var lv=new NpgsqlCommand("SELECT level FROM players WHERE id=$1",c,t)){lv.Parameters.AddWithValue(owner);ownerLevel=Convert.ToInt32(await lv.ExecuteScalarAsync(ct));}await experience.AddAsync(c,t,owner,content.Serial(35,ownerLevel)*members.Count,ct);
        foreach(var group in members.GroupBy(x=>x.player)){var level=group.First().level;await using var food=new NpgsqlCommand("UPDATE player_resources SET food=food+$2 WHERE player_id=$1",c,t);food.Parameters.AddWithValue(group.Key);food.Parameters.AddWithValue(content.Serial(36,level)*group.Count());await food.ExecuteNonQueryAsync(ct);}
        await using(var remove=new NpgsqlCommand("DELETE FROM social_teams WHERE id=$1;INSERT INTO player_quest_runtime(player_id,team_deploys) VALUES($2,1) ON CONFLICT(player_id) DO UPDATE SET team_deploys=player_quest_runtime.team_deploys+1,updated_at=now()",c,t)){remove.Parameters.AddWithValue(teamId);remove.Parameters.AddWithValue(owner);await remove.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return(await GetAsync(owner,battleId,ct),deployed);
    }

    async Task<bool> ResolveTeamDuelAsync(NpgsqlConnection c,NpgsqlTransaction t,long battleId,int battleType,int city,int joiningSide,long player,int general,CancellationToken ct)
    {
        Unit? joined=null,enemy=null;await using(var q=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 AND player_id=$2 AND general_id=$3 AND is_phantom=false FOR UPDATE",c,t)){q.Parameters.AddWithValue(battleId);q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(general);await using var r=await q.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))joined=UnitFrom(r);}await using(var q=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 AND side=$2 AND hp>0 AND detached=false ORDER BY sequence LIMIT 1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(battleId);q.Parameters.AddWithValue(joiningSide==1?2:1);await using var r=await q.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))enemy=UnitFrom(r);}if(joined is null||enemy is null)return false;
        var attacker=joiningSide==1?joined:enemy;var defender=joiningSide==1?enemy:joined;var terrain=content.WorldCities.TryGetValue(city,out var wc)?wc.Terrain:0;var result=Fight(attacker,defender,terrain);await SaveUnitAsync(c,t,attacker,ct);await SaveUnitAsync(c,t,defender,ct);await PersistForcesAsync(c,t,attacker,ct);await PersistForcesAsync(c,t,defender,ct);await AddRewardsAsync(c,t,battleId,battleType,attacker,defender,result.AttackerDamage,result.DefenderDamage,ct);
        int round;await using(var n=new NpgsqlCommand("UPDATE battles SET round_no=round_no+1 WHERE id=$1 RETURNING round_no",c,t)){n.Parameters.AddWithValue(battleId);round=Convert.ToInt32(await n.ExecuteScalarAsync(ct));}var report=JsonSerializer.Serialize(new{result.AttackerTicks,result.DefenderTicks,teamDuel=true});await using var save=new NpgsqlCommand("INSERT INTO battle_rounds(battle_id,round_no,attacker_unit_id,defender_unit_id,attacker_damage,defender_damage,attacker_hp,defender_hp,winner_side,report) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)",c,t);save.Parameters.AddWithValue(battleId);save.Parameters.AddWithValue(round);save.Parameters.AddWithValue(attacker.Id);save.Parameters.AddWithValue(defender.Id);save.Parameters.AddWithValue(result.AttackerDamage);save.Parameters.AddWithValue(result.DefenderDamage);save.Parameters.AddWithValue(attacker.Hp);save.Parameters.AddWithValue(defender.Hp);save.Parameters.AddWithValue(result.WinnerSide);save.Parameters.AddWithValue(report);await save.ExecuteNonQueryAsync(ct);return true;
    }

    public async Task<BattleView> ChooseActionAsync(long playerId,long battleId,int generalId,int actionType,int strategyId,CancellationToken ct)
    {
        if(actionType is not(1 or 2))throw new GameException("BATTLE_ACTION_INVALID","Action must be tactic or strategy.");await EnsureAsync(playerId,battleId,ct);
        await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await AuthorizeAsync(c,t,playerId,battleId,ct);
        Unit unit;await using(var cmd=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 AND player_id=$2 AND general_id=$3 AND is_phantom=false AND hp>0 AND detached=false FOR UPDATE",c,t)){cmd.Parameters.AddWithValue(battleId);cmd.Parameters.AddWithValue(playerId);cmd.Parameters.AddWithValue(generalId);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("BATTLE_UNIT_INVALID","General is not an active battle unit.");unit=UnitFrom(r);}
        var front=await FrontAsync(c,t,battleId,unit.Side,ct);if(front?.Id!=unit.Id)throw new GameException("BATTLE_ACTION_NOT_FRONT","Only the front unit may choose the combat action.");
        if(actionType==1&&(unit.TacticId==0||unit.TacticUsed))throw new GameException("BATTLE_TACTIC_UNAVAILABLE","This tactic cannot be used.");
        if(actionType==2){int city;await using(var cityCmd=new NpgsqlCommand("SELECT city_id FROM battles WHERE id=$1",c,t)){cityCmd.Parameters.AddWithValue(battleId);city=Convert.ToInt32(await cityCmd.ExecuteScalarAsync(ct));}var terrain=content.WorldCities.TryGetValue(city,out var wc)?wc.Terrain:0;if(!AllowedStrategies(unit.TroopId,terrain,unit.Side).Contains(strategyId))throw new GameException("BATTLE_STRATEGY_INVALID","Strategy is not valid for this troop and terrain.");unit.StrategyId=strategyId;}
        await using(var save=new NpgsqlCommand("UPDATE battle_units SET selected_action=$2,strategy_id=$3 WHERE id=$1",c,t)){save.Parameters.AddWithValue(unit.Id);save.Parameters.AddWithValue(actionType);save.Parameters.AddWithValue(unit.StrategyId);await save.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return await GetAsync(playerId,battleId,ct);
    }

    public async Task<int> RunQueuedDuelsAsync(long battleId,int requested,CancellationToken ct)
    {if(requested<=0)return 0;await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);int city,type,round,status;await using(var meta=new NpgsqlCommand("SELECT b.city_id,h.battle_type,b.round_no,b.status FROM battles b JOIN world_battle_handoffs h ON h.id=b.id WHERE b.id=$1 FOR UPDATE OF b",c,t)){meta.Parameters.AddWithValue(battleId);await using var r=await meta.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return 0;city=r.GetInt32(0);type=r.GetInt16(1);round=r.GetInt32(2);status=r.GetInt16(3);}if(type!=15||status!=Active)return 0;var terrain=content.WorldCities.TryGetValue(city,out var wc)?wc.Terrain:0;var completed=0;for(var i=0;i<requested;i++){Unit? a=null,d=null;await using(var units=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 AND side=1 AND hp>0 AND detached=false ORDER BY sequence DESC LIMIT 1 FOR UPDATE",c,t)){units.Parameters.AddWithValue(battleId);await using var r=await units.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))a=UnitFrom(r);}await using(var units=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 AND side=2 AND hp>0 AND detached=false ORDER BY sequence DESC LIMIT 1 FOR UPDATE",c,t)){units.Parameters.AddWithValue(battleId);await using var r=await units.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))d=UnitFrom(r);}if(a is null||d is null)break;var result=Fight(a,d,terrain);round++;await SaveUnitAsync(c,t,a,ct);await SaveUnitAsync(c,t,d,ct);await using(var detach=new NpgsqlCommand("UPDATE battle_units SET detached=true WHERE id IN($1,$2)",c,t)){detach.Parameters.AddWithValue(a.Id);detach.Parameters.AddWithValue(d.Id);await detach.ExecuteNonQueryAsync(ct);}await PersistForcesAsync(c,t,a,ct);await AddRewardsAsync(c,t,battleId,type,a,d,result.AttackerDamage,result.DefenderDamage,ct);if(d.EventNpcId.HasValue&&a.PlayerId.HasValue)await nationProgress.RecordScheduledWorldEventDamageAsync(c,t,battleId,round,d.EventNpcId.Value,a.PlayerId.Value,result.DefenderDamage,d.Hp<=0,ct);var report=JsonSerializer.Serialize(new{result.AttackerTicks,result.DefenderTicks,forcedDuel=true});await using var save=new NpgsqlCommand("INSERT INTO battle_rounds(battle_id,round_no,attacker_unit_id,defender_unit_id,attacker_damage,defender_damage,attacker_hp,defender_hp,winner_side,report) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb);UPDATE battles SET round_no=$2 WHERE id=$1",c,t);save.Parameters.AddWithValue(battleId);save.Parameters.AddWithValue(round);save.Parameters.AddWithValue(a.Id);save.Parameters.AddWithValue(d.Id);save.Parameters.AddWithValue(result.AttackerDamage);save.Parameters.AddWithValue(result.DefenderDamage);save.Parameters.AddWithValue(a.Hp);save.Parameters.AddWithValue(d.Hp);save.Parameters.AddWithValue(result.WinnerSide);save.Parameters.AddWithValue(report);await save.ExecuteNonQueryAsync(ct);completed++;}await t.CommitAsync(ct);return completed;}

    async Task EnsureAsync(long playerId, long battleId, CancellationToken ct)
    {
        await using var c = await db.DataSource.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct);
        long attackerPlayer; int attackerGeneral, attackerForce, defenderForce, city, handoffStatus, battleType;
        await using (var cmd = new NpgsqlCommand("SELECT attacker_player_id,attacker_general_id,attacker_force_id,defender_force_id,city_id,status,battle_type FROM world_battle_handoffs WHERE id=$1 FOR UPDATE", c, t))
        { cmd.Parameters.AddWithValue(battleId); await using var r=await cmd.ExecuteReaderAsync(ct); if(!await r.ReadAsync(ct)) throw new GameException("BATTLE_NOT_FOUND","Battle does not exist.",404); attackerPlayer=r.GetInt64(0); attackerGeneral=r.GetInt32(1); attackerForce=r.GetInt16(2); defenderForce=r.GetInt16(3); city=r.GetInt32(4); handoffStatus=r.GetInt16(5); battleType=r.GetInt16(6); }
        if (attackerPlayer != playerId && battleType is not(16 or 17 or 18)) throw new GameException("BATTLE_FORBIDDEN","You are not a participant.",403);
        if (handoffStatus != 0) { await t.CommitAsync(ct); return; }
        await using (var exists = new NpgsqlCommand("SELECT 1 FROM battles WHERE id=$1",c,t)) { exists.Parameters.AddWithValue(battleId); if(await exists.ExecuteScalarAsync(ct) is not null){await t.CommitAsync(ct);return;} }
        await using (var add = new NpgsqlCommand("INSERT INTO battles(id,city_id) VALUES($1,$2)",c,t)){add.Parameters.AddWithValue(battleId);add.Parameters.AddWithValue(city);await add.ExecuteNonQueryAsync(ct);}
        await AddPlayerUnitAsync(c,t,battleId,1,0,attackerPlayer,attackerGeneral,city,ct);
        if(battleType is 16 or 17 or 18){var extra=new List<int>();await using(var q=new NpgsqlCommand("SELECT value::integer FROM world_battle_handoffs h CROSS JOIN LATERAL jsonb_array_elements_text(h.result_payload->'attackerGenerals') value WHERE h.id=$1 AND value::integer<>h.attacker_general_id",c,t)){q.Parameters.AddWithValue(battleId);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))extra.Add(r.GetInt32(0));}var n=1;foreach(var general in extra)await AddPlayerUnitAsync(c,t,battleId,1,n++,attackerPlayer,general,city,ct);}
        var sequence=0;
        if(battleType==14){var trialArmies=new List<int>();await using(var trial=new NpgsqlCommand("SELECT army_id FROM nation_trial_npcs WHERE force_id=$1 AND city_id=$2 AND defeated=false UNION ALL SELECT n.army_id FROM nation_protections p JOIN nation_trial_npcs n ON n.force_id=p.attacking_force_id AND n.city_id=p.city_id AND n.defeated=false WHERE p.force_id=$1 AND p.city_id=$2 AND p.won IS NULL UNION ALL SELECT army_id FROM nation_task_npcs WHERE force_id=$1 AND city_id=$2 AND defeated=false ORDER BY army_id",c,t)){trial.Parameters.AddWithValue(attackerForce);trial.Parameters.AddWithValue(city);await using var r=await trial.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))trialArmies.Add(r.GetInt32(0));}foreach(var armyId in trialArmies)if(content.Armies.TryGetValue(armyId,out var army))await AddNpcUnitAsync(c,t,battleId,sequence++,army,ct);}
        if(battleType==15){var eventUnits=new List<(long id,int army)>();await using(var scheduled=new NpgsqlCommand("SELECT n.id,n.army_id FROM world_battle_handoffs h JOIN nation_event_npcs selected ON selected.id=(h.result_payload->>'eventNpcId')::bigint JOIN nation_event_npcs n ON n.scheduled_task_id=selected.scheduled_task_id AND n.city_id=selected.city_id AND n.defeated=false WHERE h.id=$1 ORDER BY n.id FOR UPDATE OF n",c,t)){scheduled.Parameters.AddWithValue(battleId);await using var r=await scheduled.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))eventUnits.Add((r.GetInt64(0),r.GetInt32(1)));}foreach(var eventUnit in eventUnits)if(content.Armies.TryGetValue(eventUnit.army,out var army)){var unitSequence=sequence++;await AddNpcUnitAsync(c,t,battleId,unitSequence,army,ct);await using var source=new NpgsqlCommand("UPDATE battle_units SET event_npc_id=$4 WHERE battle_id=$1 AND side=2 AND sequence=$2 AND general_id=$3",c,t);source.Parameters.AddWithValue(battleId);source.Parameters.AddWithValue(unitSequence);source.Parameters.AddWithValue(army.GeneralId);source.Parameters.AddWithValue(eventUnit.id);await source.ExecuteNonQueryAsync(ct);}}
        var defenders = new List<(long player,int general)>();
        if(battleType is 6 or 7 or 16 or 17 or 18)await using(var kf=new NpgsqlCommand("SELECT (h.result_payload->>'defenderPlayerId')::bigint,value::integer FROM world_battle_handoffs h CROSS JOIN LATERAL jsonb_array_elements_text(h.result_payload->'defenderGenerals') value WHERE h.id=$1",c,t)){kf.Parameters.AddWithValue(battleId);await using var r=await kf.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))defenders.Add((r.GetInt64(0),r.GetInt32(1)));}
        var defenderSql=battleType==4?"SELECT pg.player_id,pg.general_id FROM player_office_memberships m JOIN player_generals pg ON pg.player_id=m.player_id WHERE m.force_id=$1 AND m.building_id=$2 AND m.state=1 AND pg.general_type=2 ORDER BY m.is_leader DESC,pg.player_id,pg.general_id":"SELECT pg.player_id,pg.general_id FROM player_generals pg JOIN players p ON p.id=pg.player_id WHERE p.force_id=$1 AND pg.location_id=$2 AND pg.general_type=2 AND pg.state<=1 ORDER BY pg.player_id,pg.general_id";
        if(sequence==0&&battleType is not(6 or 7 or 16 or 17 or 18))await using (var cmd = new NpgsqlCommand(defenderSql,c,t))
        {cmd.Parameters.AddWithValue(battleType==4?attackerForce:defenderForce);cmd.Parameters.AddWithValue(city);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))defenders.Add((r.GetInt64(0),r.GetInt32(1)));}
        foreach(var d in defenders) await AddPlayerUnitAsync(c,t,battleId,2,sequence++,d.player,d.general,city,ct);
        if(sequence==0&&battleType==4&&content.Halls.TryGetValue((city,1),out var hall)){foreach(var value in hall.Npcs.Split(';',StringSplitOptions.RemoveEmptyEntries))if(int.TryParse(value,out var armyId)&&content.Armies.TryGetValue(armyId,out var army))await AddNpcUnitAsync(c,t,battleId,sequence++,army,ct);if(content.Armies.TryGetValue(hall.Chief,out var chief))await AddNpcUnitAsync(c,t,battleId,sequence++,chief,ct);}
        if(sequence==0 && battleType is not(4 or 6 or 7) && content.WorldCities.TryGetValue(city,out var definition)) foreach(var armyId in definition.Npcs) if(content.Armies.TryGetValue(armyId,out var army)) await AddNpcUnitAsync(c,t,battleId,sequence++,army,ct);
        if(sequence==0) throw new GameException("BATTLE_DEFENDER_MISSING","Legacy city has no defender data.",500);
        await t.CommitAsync(ct);
    }

    async Task AddPlayerUnitAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,int side,int sequence,long player,int generalId,int city,CancellationToken ct)
    {
        int level,forces,leaderBonus,strengthBonus; await using(var cmd=new NpgsqlCommand("SELECT level,forces,leader_bonus,strength_bonus FROM player_generals WHERE player_id=$1 AND general_id=$2 FOR UPDATE",c,t)){cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(generalId);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("BATTLE_GENERAL_MISSING","Battle general does not exist.");level=r.GetInt32(0);forces=r.GetInt32(1);leaderBonus=r.GetInt32(2);strengthBonus=r.GetInt32(3);}
        if(!content.Generals.TryGetValue(generalId,out var g)||!content.Troops.TryGetValue(g.TroopId,out var troop))throw new GameException("BATTLE_STATIC_MISSING","General troop data is missing.",500);
        var equip=await EquipmentAsync(c,t,player,generalId,ct);var equipSkills=await EquipmentSkillEffectService.BattleAsync(c,t,content,player,generalId,ct);var techAtt=await technologies.GetCompletedIntEffectAsync(player,30,0,ct,c,t);var techDef=await technologies.GetCompletedIntEffectAsync(player,30,1,ct,c,t);var techHp=await technologies.GetCompletedIntEffectAsync(player,30,2,ct,c,t);var columns=2+await technologies.GetCompletedIntEffectAsync(player,4,0,ct,c,t);
        var techTacticAtt=await technologies.GetCompletedIntEffectAsync(player,10,0,ct,c,t);var techTacticDef=await technologies.GetCompletedIntEffectAsync(player,13,0,ct,c,t);
        var max=MaxHp(level,equip.hp+equipSkills.Blood+techHp,columns); var hp=Math.Min(max,forces>0?forces:max); hp-=hp%3;
        content.Tactics.TryGetValue(g.TacticId,out var tactic); var strategy=DefaultStrategy(troop,content.WorldCities.TryGetValue(city,out var wc)?wc.Terrain:0,side);
        var treasure=await treasures.BattleEffectAsync(c,t,player,ct);var attack=(int)((150+(level-1)*3+troop.Attack+equip.att+equipSkills.Attack+techAtt+treasure.AttackBase)*treasure.AttackCoefficient);var defense=(int)((50+(level-1)+troop.Defense+equip.def+equipSkills.Defense+techDef+treasure.DefenseBase)*treasure.DefenseCoefficient);await InsertUnitAsync(c,t,battle,side,sequence,player,g.Id,g.TroopId,g.Name,level,attack,defense,g.Leader+leaderBonus,g.Strength+strengthBonus,hp,max,false,g.Quality,g.TacticId,tactic?.DamageExponent??0,tactic?.Range??0,strategy,techTacticAtt,techTacticDef,equipSkills.AttackBonus,equipSkills.DefenseBonus,equipSkills.TacticAttack,equipSkills.TacticDefense,ct);
    }
    async Task AddNpcUnitAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,int sequence,ArmyDefinition army,CancellationToken ct)
    { var effects=army.Effect.Split(';').Select(x=>x.Split('=')).Where(x=>x.Length==2).ToDictionary(x=>x[0],x=>int.TryParse(x[1],out var n)?n:0); content.Generals.TryGetValue(army.GeneralId,out var g);content.Tactics.TryGetValue(g?.TacticId??0,out var tactic);await InsertUnitAsync(c,t,battle,2,sequence,null,army.GeneralId,army.TroopId,army.Name,army.GeneralLevel,effects.GetValueOrDefault("att"),effects.GetValueOrDefault("def"),30,30,army.ArmyHp,army.ArmyHp,true,g?.Quality??0,g?.TacticId??0,tactic?.DamageExponent??0,tactic?.Range??0,0,0,0,0,0,0,0,ct); }
    static async Task InsertUnitAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,int side,int seq,long? player,int general,int troop,string name,int level,int att,int def,int leader,int strength,int hp,int max,bool npc,int quality,int tactic,double tacticDamage,int tacticRange,int strategy,int techTacticAtt,int techTacticDef,int equipAttB,int equipDefB,int equipTacticAtt,int equipTacticDef,CancellationToken ct)
    {await using var cmd=new NpgsqlCommand("INSERT INTO battle_units(battle_id,side,sequence,player_id,general_id,troop_id,name,level,attack,defense,leader,strength,hp,max_hp,is_npc,quality,tactic_id,tactic_damage,tactic_range,strategy_id,tech_tactic_attack,tech_tactic_defense,equip_att_b,equip_def_b,equip_tactic_att,equip_tactic_def) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26)",c,t);cmd.Parameters.AddWithValue(battle);cmd.Parameters.AddWithValue(side);cmd.Parameters.AddWithValue(seq);cmd.Parameters.AddWithValue((object?)player??DBNull.Value);cmd.Parameters.AddWithValue(general);cmd.Parameters.AddWithValue(troop);cmd.Parameters.AddWithValue(name);cmd.Parameters.AddWithValue(level);cmd.Parameters.AddWithValue(att);cmd.Parameters.AddWithValue(def);cmd.Parameters.AddWithValue(leader);cmd.Parameters.AddWithValue(strength);cmd.Parameters.AddWithValue(hp);cmd.Parameters.AddWithValue(max);cmd.Parameters.AddWithValue(npc);cmd.Parameters.AddWithValue(quality);cmd.Parameters.AddWithValue(tactic);cmd.Parameters.AddWithValue(tacticDamage);cmd.Parameters.AddWithValue(tacticRange);cmd.Parameters.AddWithValue(strategy);cmd.Parameters.AddWithValue(techTacticAtt);cmd.Parameters.AddWithValue(techTacticDef);cmd.Parameters.AddWithValue(equipAttB);cmd.Parameters.AddWithValue(equipDefB);cmd.Parameters.AddWithValue(equipTacticAtt);cmd.Parameters.AddWithValue(equipTacticDef);await cmd.ExecuteNonQueryAsync(ct);}
    static int MaxHp(int level,int bonus,int columns){var hp=(1200+(level-1)*24+bonus)/3*Math.Max(1,columns)*3;return hp-hp%6;}

    static async Task<(int att,int def,int hp)> EquipmentAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int general,CancellationToken ct)
    {await using var cmd=new NpgsqlCommand(@"SELECT COALESCE(sum(CASE WHEN goods_type IN(1,2) THEN attribute ELSE 0 END),0),COALESCE(sum(CASE WHEN goods_type IN(3,4) THEN attribute ELSE 0 END),0),COALESCE(sum(CASE WHEN goods_type NOT IN(1,2,3,4,10,14) THEN attribute ELSE 0 END),0) FROM player_equipment WHERE player_id=$1 AND owner_general_id=$2",c,t);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(general);await using var r=await cmd.ExecuteReaderAsync(ct);await r.ReadAsync(ct);return((int)r.GetInt64(0),(int)r.GetInt64(1),(int)r.GetInt64(2));}
    static int DefaultStrategy(TroopDefinition troop,int terrain,int side)=>ParseStrategies(troop,terrain,side).FirstOrDefault();
    static int[] ParseStrategies(TroopDefinition troop,int terrain,int side){var raw=side==1?troop.TerrainStrategy:troop.TerrainStrategyDefense;foreach(var group in raw.Split(';')){var p=group.Split('|');if(p.Length<2||!int.TryParse(p[0],out var id)||id!=terrain)continue;return p[1].Split(',').Select(x=>int.TryParse(x,out var value)?value:0).Where(x=>x!=0).Distinct().ToArray();}return [];}
    int[] AllowedStrategies(int troopId,int terrain,int side)=>content.Troops.TryGetValue(troopId,out var troop)?ParseStrategies(troop,terrain,side):[];

    StrategyDamage ApplyStrategy(Unit a,Unit d)
    {if(!content.FightStrategyCoefficients.TryGetValue((a.StrategyId,d.StrategyId),out var coe))return new(0,0);var toA=Math.Min(a.Hp,(int)(a.Hp*coe.AttackerLost));var toD=Math.Min(d.Hp,(int)(d.Hp*coe.DefenderLost));a.Hp-=toA;d.Hp-=toD;return new(toA,toD);}

    async Task<EffectDamage> ApplyTacticsAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,Unit a,Unit d,int terrain,CancellationToken ct)
    {var ar=await ApplyTacticAsync(c,t,battle,a,d,terrain,ct);var dr=await ApplyTacticAsync(c,t,battle,d,a,terrain,ct);return new(dr.damage,ar.damage,ar.stopped,dr.stopped);}
    async Task<(int damage,bool stopped)> ApplyTacticAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,Unit source,Unit opposingFront,int terrain,CancellationToken ct)
    {
        if((source.PlayerId is not null&&source.SelectedAction!=1)||source.TacticUsed||source.TacticId==0||source.TacticRange<=0||source.Hp<=0)return(0,false);
        var stopped=false;if(source.Quality>3&&opposingFront.Quality>3){var diff=source.Strength-opposingFront.Strength;var chance=Math.Clamp(.05-(diff<0?.02:.01)*diff,.01,.5);stopped=Random.Shared.NextDouble()<chance;}
        var total=0;if(!stopped){var targets=new List<Unit>();await using(var cmd=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 AND side=$2 AND hp>0 AND detached=false ORDER BY sequence LIMIT $3 FOR UPDATE",c,t)){cmd.Parameters.AddWithValue(battle);cmd.Parameters.AddWithValue(opposingFront.Side);cmd.Parameters.AddWithValue(source.TacticRange);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))targets.Add(UnitFrom(r));}var append=source.TacticRange>targets.Count&&targets.Count>0?(double)source.TacticRange/targets.Count:1;foreach(var target in targets){double damage=Math.Max(source.Attack-target.Defense,0);damage*=Math.Pow(Math.Max(source.TacticDamage,0),.5);damage*=append;damage*=Math.Clamp(1+.01*(source.TechTacticAttack-target.TechTacticDefense),.5,2);if(source.Side==1)damage*=.5;damage=ApplyLegacyDirectBonus(damage,source.EquipTacticAttack-target.EquipTacticDefense);var dealt=Math.Min(target.Hp,Math.Max(0,(int)damage));target.Hp-=dealt;if(target.Id==opposingFront.Id)opposingFront.Hp=target.Hp;total+=dealt;await SaveUnitAsync(c,t,target,ct);await PersistForcesAsync(c,t,target,ct);}}
        source.TacticUsed=true;await using(var used=new NpgsqlCommand("UPDATE battle_units SET tactic_used=true WHERE id=$1",c,t)){used.Parameters.AddWithValue(source.Id);await used.ExecuteNonQueryAsync(ct);}return(total,stopped);
    }

    async Task AddRewardsAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,int battleType,Unit a,Unit d,int lostA,int lostD,CancellationToken ct)
    {if(content.FightRewardCoefficients.TryGetValue(battleType,out var reward)){await RewardOneAsync(c,t,battle,a,d,lostA,lostD,reward,ct);await RewardOneAsync(c,t,battle,d,a,lostD,lostA,reward,ct);}if(battleType==18){await AwardTroopDropAsync(c,t,battle,a,d,ct);await AwardTroopDropAsync(c,t,battle,d,a,ct);}}
    async Task<double> FarmExpRateAsync(NpgsqlConnection c,NpgsqlTransaction t,Unit unit,CancellationToken ct)
    {if(unit.PlayerId is null||unit.IsPhantom)return 0;await using var q=new NpgsqlCommand("SELECT 1 FROM player_farm_buffs WHERE player_id=$1 AND general_id=$2 AND expires_at>now()",c,t);q.Parameters.AddWithValue(unit.PlayerId.Value);q.Parameters.AddWithValue(unit.GeneralId);return await q.ExecuteScalarAsync(ct)is null?0:.5;}
    async Task RewardOneAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,Unit unit,Unit enemy,int ownLost,int enemyLost,FightRewardCoefficientDefinition reward,CancellationToken ct)
    {if(unit.PlayerId is null||!content.TroopConscripts.TryGetValue(unit.TroopId,out var ownFood)||!content.TroopConscripts.TryGetValue(enemy.TroopId,out var enemyFood))return;var foodA=ownFood.Food*ownLost;var foodB=enemyFood.Food*enemyLost;var ratio=Math.Clamp(foodB/(1+foodA),.5,2);var damageCoe=1+reward.Delta*.5*(ratio-1);var level=unit.Level>enemy.Level+5?-1:unit.Level>enemy.Level?-.2*(unit.Level-enemy.Level):0;var value=damageCoe*(1+reward.LevelCoefficient*level)*foodA;var copper=Math.Max(0,(int)(value*reward.M));var activityRate=await battleExpActivity.MultiplierAsync(c,t,unit.PlayerId.Value,unit.Level,ct);var farmRate=await FarmExpRateAsync(c,t,unit,ct);var playerExp=Math.Max(0,(int)(value*reward.C*(1+activityRate+farmRate)));var generalBonus=await technologies.GetCompletedIntEffectAsync(unit.PlayerId.Value,16,0,ct,c,t);var generalExp=Math.Max(0,(int)(value*reward.E*(1+generalBonus/100d+farmRate)));await using(var cmd=new NpgsqlCommand(@"INSERT INTO battle_rewards(battle_id,player_id,general_id,copper,player_exp,general_exp) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(battle_id,player_id,general_id) DO UPDATE SET copper=battle_rewards.copper+excluded.copper,player_exp=battle_rewards.player_exp+excluded.player_exp,general_exp=battle_rewards.general_exp+excluded.general_exp;UPDATE player_resources SET copper=copper+$4 WHERE player_id=$2",c,t)){cmd.Parameters.AddWithValue(battle);cmd.Parameters.AddWithValue(unit.PlayerId.Value);cmd.Parameters.AddWithValue(unit.GeneralId);cmd.Parameters.AddWithValue(copper);cmd.Parameters.AddWithValue(playerExp);cmd.Parameters.AddWithValue(generalExp);await cmd.ExecuteNonQueryAsync(ct);}await AddGeneralExperienceAsync(c,t,unit.PlayerId.Value,unit.GeneralId,generalExp,ct);await experience.AddAsync(c,t,unit.PlayerId.Value,playerExp,ct);}

    async Task AwardTroopDropAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,Unit winner,Unit killed,CancellationToken ct)
    {
        if(winner.PlayerId is null||killed.Hp>0||!content.Troops.TryGetValue(killed.TroopId,out var troop)||string.IsNullOrWhiteSpace(troop.Drop))return;
        foreach(var raw in troop.Drop.Split(';',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries))
        {
            var p=raw.Split(',',StringSplitOptions.TrimEntries);if(p.Length<2||!int.TryParse(p[1],out var amount)||amount<=0)continue;
            var type=p[0].ToLowerInvariant() switch{"copper"=>1001,"lumber"=>1002,"food"=>1003,"iron"=>1004,"chiefexp"=>1005,_=>0};if(type==0)continue;
            await using(var grant=new NpgsqlCommand("INSERT INTO battle_troop_drop_grants(battle_id,killed_unit_id,player_id,drop_type,amount) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING",c,t)){grant.Parameters.AddWithValue(battle);grant.Parameters.AddWithValue(killed.Id);grant.Parameters.AddWithValue(winner.PlayerId.Value);grant.Parameters.AddWithValue(type);grant.Parameters.AddWithValue(amount);if(await grant.ExecuteNonQueryAsync(ct)!=1)continue;}
            if(type==1005){await experience.AddAsync(c,t,winner.PlayerId.Value,amount,ct);continue;}
            var column=type switch{1001=>"copper",1002=>"wood",1003=>"food",1004=>"iron",_=>throw new InvalidOperationException()};await using var add=new NpgsqlCommand($"UPDATE player_resources SET {column}={column}+$2,update_time=now() WHERE player_id=$1",c,t);add.Parameters.AddWithValue(winner.PlayerId.Value);add.Parameters.AddWithValue(amount);await add.ExecuteNonQueryAsync(ct);
        }
    }

    async Task AddGeneralExperienceAsync(NpgsqlConnection c,NpgsqlTransaction t,long playerId,int generalId,int amount,CancellationToken ct)
    {if(amount<=0||!content.Generals.TryGetValue(generalId,out var definition))return;int playerLevel,level;long exp;await using(var cmd=new NpgsqlCommand("SELECT p.level,g.level,g.exp FROM players p JOIN player_generals g ON g.player_id=p.id AND g.general_id=$2 WHERE p.id=$1 FOR UPDATE OF g,p",c,t)){cmd.Parameters.AddWithValue(playerId);cmd.Parameters.AddWithValue(generalId);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return;playerLevel=r.GetInt32(0);level=r.GetInt32(1);exp=r.GetInt64(2);}exp+=amount;while(level<playerLevel){int need;try{need=content.Serial(definition.UpgradeExpSeriesId,level);}catch{break;}if(exp<need)break;exp-=need;level++;}if(level>=playerLevel){try{exp=Math.Min(exp,content.Serial(definition.UpgradeExpSeriesId,level));}catch{}}await using var save=new NpgsqlCommand("UPDATE player_generals SET level=$3,exp=$4,updated_at=now() WHERE player_id=$1 AND general_id=$2",c,t);save.Parameters.AddWithValue(playerId);save.Parameters.AddWithValue(generalId);save.Parameters.AddWithValue(level);save.Parameters.AddWithValue(exp);await save.ExecuteNonQueryAsync(ct);}

    sealed class Unit{public long Id;public int Side,Sequence,GeneralId,TroopId,Level,Attack,Defense,Leader,Strength,Hp,MaxHp,Quality,TacticId,TacticRange,StrategyId,TechTacticAttack,TechTacticDefense,EquipAttackBonus,EquipDefenseBonus,EquipTacticAttack,EquipTacticDefense,SelectedAction;public double TacticDamage;public bool TacticUsed,Detached,IsPhantom;public long? PlayerId,EventNpcId;public string Name="";public bool IsNpc;}
    sealed record EffectDamage(int ToAttacker,int ToDefender,bool AttackerStopped,bool DefenderStopped);
    sealed record StrategyDamage(int ToAttacker,int ToDefender);
    sealed record FightResult(int AttackerDamage,int DefenderDamage,int WinnerSide,int[] AttackerTicks,int[] DefenderTicks);
    FightResult Fight(Unit a,Unit d,int terrain){var ah=a.Hp;var dh=d.Hp;var at=new List<int>();var dt=new List<int>();for(var i=1;i<7&&ah>0&&dh>0;i++){var toDef=Damage(a,d,ah,dh,Terrain(a.TroopId,terrain,true),Terrain(d.TroopId,terrain,false));var toAtt=Damage(d,a,dh,ah,Terrain(d.TroopId,terrain,false),Terrain(a.TroopId,terrain,true));dh-=toDef;ah-=toAtt;at.Add(toAtt);dt.Add(toDef);}if(ah>0&&dh>0){if(ah>dh){ah-=dh;dh=0;}else if(dh>ah){dh-=ah;ah=0;}else{ah=0;dh=0;}}var ad=a.Hp-ah;var dd=d.Hp-dh;a.Hp=ah;d.Hp=dh;return new(ad,dd,ah>dh?1:dh>ah?2:3,at.ToArray(),dt.ToArray());}
    int Damage(Unit a,Unit b,int ah,int bh,double at,double bt){if(ah==0||bh==0)return 0;double damage=Math.Max(a.Attack-b.Defense,0);damage*=.9+.2*Random.Shared.NextDouble();var blood=Math.Clamp(Math.Pow((double)ah/bh,.25),.2,5);damage*=blood;damage*=Math.Clamp(1+at-bt,.6,1.6);damage*=Math.Clamp(1+(a.Leader-b.Leader)*.005,.65,1.35);damage=ApplyLegacyDirectBonus(damage,a.EquipAttackBonus-b.EquipDefenseBonus);damage=Math.Max(1,damage);return Math.Min(bh,(int)damage);}
    static double ApplyLegacyDirectBonus(double baseDamage,int delta){var damage=baseDamage+delta;if(damage<baseDamage*.1)damage=baseDamage*.1;else if(damage>baseDamage*3)damage=baseDamage*3;if(damage<delta*.5)damage=delta*.5;return damage;}
    double Terrain(int troopId,int terrain,bool attacker){if(!content.Troops.TryGetValue(troopId,out var troop))return 0;foreach(var item in troop.TerrainSpec.Split(';')){var p=item.Split(',');if(p.Length>=6&&int.TryParse(p[0],out var id)&&id==terrain&&int.TryParse(p[attacker?3:4],out var value))return value/100d;}return 0;}
    const string UnitColumns="id,side,sequence,player_id,general_id,troop_id,name,level,attack,defense,leader,strength,hp,max_hp,is_npc,quality,tactic_id,tactic_damage,tactic_range,tactic_used,strategy_id,tech_tactic_attack,tech_tactic_defense,selected_action,event_npc_id,detached,is_phantom,equip_att_b,equip_def_b,equip_tactic_att,equip_tactic_def";
    static async Task<Unit?> FrontAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,int side,CancellationToken ct){await using var cmd=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 AND side=$2 AND hp>0 AND detached=false ORDER BY sequence LIMIT 1 FOR UPDATE",c,t);cmd.Parameters.AddWithValue(battle);cmd.Parameters.AddWithValue(side);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;return UnitFrom(r);}
    static Unit UnitFrom(NpgsqlDataReader r)=>new(){Id=r.GetInt64(0),Side=r.GetInt16(1),Sequence=r.GetInt32(2),PlayerId=r.IsDBNull(3)?null:r.GetInt64(3),GeneralId=r.GetInt32(4),TroopId=r.GetInt32(5),Name=r.GetString(6),Level=r.GetInt32(7),Attack=r.GetInt32(8),Defense=r.GetInt32(9),Leader=r.GetInt32(10),Strength=r.GetInt32(11),Hp=r.GetInt32(12),MaxHp=r.GetInt32(13),IsNpc=r.GetBoolean(14),Quality=r.GetInt32(15),TacticId=r.GetInt32(16),TacticDamage=r.GetDouble(17),TacticRange=r.GetInt32(18),TacticUsed=r.GetBoolean(19),StrategyId=r.GetInt32(20),TechTacticAttack=r.GetInt32(21),TechTacticDefense=r.GetInt32(22),SelectedAction=r.GetInt16(23),EventNpcId=r.IsDBNull(24)?null:r.GetInt64(24),Detached=r.GetBoolean(25),IsPhantom=r.GetBoolean(26),EquipAttackBonus=r.GetInt32(27),EquipDefenseBonus=r.GetInt32(28),EquipTacticAttack=r.GetInt32(29),EquipTacticDefense=r.GetInt32(30)};
    static async Task SaveUnitAsync(NpgsqlConnection c,NpgsqlTransaction t,Unit u,CancellationToken ct){await using var cmd=new NpgsqlCommand("UPDATE battle_units SET hp=$2 WHERE id=$1",c,t);cmd.Parameters.AddWithValue(u.Id);cmd.Parameters.AddWithValue(u.Hp);await cmd.ExecuteNonQueryAsync(ct);}
    static async Task PersistForcesAsync(NpgsqlConnection c,NpgsqlTransaction t,Unit u,CancellationToken ct){if(u.PlayerId is null||u.IsPhantom)return;await using var cmd=new NpgsqlCommand("UPDATE player_generals SET forces=$3,updated_at=now() WHERE player_id=$1 AND general_id=$2",c,t);cmd.Parameters.AddWithValue(u.PlayerId.Value);cmd.Parameters.AddWithValue(u.GeneralId);cmd.Parameters.AddWithValue(u.Hp);await cmd.ExecuteNonQueryAsync(ct);}
    static async Task<bool> HasAliveAsync(NpgsqlConnection c,NpgsqlTransaction t,long battle,int side,CancellationToken ct){await using var cmd=new NpgsqlCommand("SELECT EXISTS(SELECT 1 FROM battle_units WHERE battle_id=$1 AND side=$2 AND hp>0 AND detached=false)",c,t);cmd.Parameters.AddWithValue(battle);cmd.Parameters.AddWithValue(side);return (bool)(await cmd.ExecuteScalarAsync(ct))!;}
    static async Task AuthorizeAsync(NpgsqlConnection c,NpgsqlTransaction? t,long player,long battle,CancellationToken ct){await using var cmd=new NpgsqlCommand("SELECT 1 FROM battle_units WHERE battle_id=$1 AND player_id=$2 AND is_phantom=false",c,t);cmd.Parameters.AddWithValue(battle);cmd.Parameters.AddWithValue(player);if(await cmd.ExecuteScalarAsync(ct)is null)throw new GameException("BATTLE_FORBIDDEN","You are not a participant.",403);}

    async Task<BattleView> ReadAsync(NpgsqlConnection c,NpgsqlTransaction? t,long battle,CancellationToken ct)
    {
        int city,status,round;int? winner;await using(var cmd=new NpgsqlCommand("SELECT city_id,status,round_no,winner_side FROM battles WHERE id=$1",c,t)){cmd.Parameters.AddWithValue(battle);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("BATTLE_NOT_FOUND","Battle does not exist.",404);city=r.GetInt32(0);status=r.GetInt16(1);round=r.GetInt32(2);winner=r.IsDBNull(3)?null:r.GetInt16(3);}
        int battleType;await using(var typeCmd=new NpgsqlCommand("SELECT battle_type FROM world_battle_handoffs WHERE id=$1",c,t)){typeCmd.Parameters.AddWithValue(battle);battleType=Convert.ToInt32(await typeCmd.ExecuteScalarAsync(ct));}var terrain=battleType==4?6:battleType is 6 or 7?9:content.WorldCities.TryGetValue(city,out var wc)?wc.Terrain:0;var units=new List<BattleUnitView>();
        await using(var cmd=new NpgsqlCommand($"SELECT {UnitColumns} FROM battle_units WHERE battle_id=$1 ORDER BY side,sequence",c,t)){cmd.Parameters.AddWithValue(battle);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var u=UnitFrom(r);units.Add(new(u.Id,u.Side,u.Sequence,u.PlayerId,u.GeneralId,u.TroopId,u.Name,u.Level,u.Attack,u.Defense,u.Leader,u.Strength,u.Hp,u.MaxHp,u.IsNpc,u.Hp<=0,u.TacticId,!u.TacticUsed&&u.TacticId!=0,u.StrategyId,AllowedStrategies(u.TroopId,terrain,u.Side),u.SelectedAction));}}
        var rounds=new List<BattleRoundView>();await using(var cmd=new NpgsqlCommand("SELECT round_no,attacker_unit_id,defender_unit_id,attacker_damage,defender_damage,attacker_hp,defender_hp,winner_side,report FROM battle_rounds WHERE battle_id=$1 ORDER BY round_no",c,t)){cmd.Parameters.AddWithValue(battle);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){using var json=JsonDocument.Parse(r.GetString(8));var root=json.RootElement;rounds.Add(new(r.GetInt32(0),r.GetInt64(1),r.GetInt64(2),r.GetInt32(3),r.GetInt32(4),r.GetInt32(5),r.GetInt32(6),r.GetInt16(7),root.GetProperty("AttackerTicks").EnumerateArray().Select(x=>x.GetInt32()).ToArray(),root.GetProperty("DefenderTicks").EnumerateArray().Select(x=>x.GetInt32()).ToArray()));}}
        return new(battle,city,status,round,winner,units.Where(x=>x.Side==1).ToArray(),units.Where(x=>x.Side==2).ToArray(),rounds);
    }
}
