using CTXD.Server.Data;using Npgsql;
namespace CTXD.Server.Services;
public sealed record BattleExpActivityView(long ActivityId,bool Active,bool Activated,string Condition,int AddPercent,DateTimeOffset EndsAt);
public sealed class BattleExpActivityService(GameDb db,GamePushHub push)
{
 static readonly TimeSpan LegacyOffset=TimeSpan.FromHours(8);static DateOnly Day()=>DateOnly.FromDateTime(DateTimeOffset.UtcNow.ToOffset(LegacyOffset).Date);
 public async Task<BattleExpActivityView> GetAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);int level;await using(var p=new NpgsqlCommand("SELECT level FROM players WHERE id=$1",c)){p.Parameters.AddWithValue(player);level=Convert.ToInt32(await p.ExecuteScalarAsync(ct));}var activity=await ActiveAsync(c,null,ct);if(activity is null)return new(0,false,false,Condition(level),Percent(level),DateTimeOffset.MinValue);await using var q=new NpgsqlCommand("SELECT 1 FROM player_battle_exp_activity WHERE player_id=$1 AND activity_id=$2 AND active_day=$3",c);q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(activity.Value.id);q.Parameters.AddWithValue(Day().ToDateTime(TimeOnly.MinValue));return new(activity.Value.id,true,await q.ExecuteScalarAsync(ct)is not null,Condition(level),Percent(level),activity.Value.end);}
 public async Task<BattleExpActivityView> ActivateAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);int level;await using(var p=new NpgsqlCommand("SELECT level FROM players WHERE id=$1 FOR UPDATE",c,t)){p.Parameters.AddWithValue(player);level=Convert.ToInt32(await p.ExecuteScalarAsync(ct));}if(level<55)throw new GameException("BATTLE_EXP_LEVEL_LOW","Legacy battle EXP activity requires level 55.");var activity=await ActiveAsync(c,t,ct)??throw new GameException("BATTLE_EXP_INACTIVE","Battle EXP activity is not active.");await using(var add=new NpgsqlCommand("INSERT INTO player_battle_exp_activity(player_id,activity_id,active_day) VALUES($1,$2,$3) ON CONFLICT DO NOTHING",c,t)){add.Parameters.AddWithValue(player);add.Parameters.AddWithValue(activity.id);add.Parameters.AddWithValue(Day().ToDateTime(TimeOnly.MinValue));if(await add.ExecuteNonQueryAsync(ct)!=1)throw new GameException("BATTLE_EXP_ALREADY_ACTIVE","Battle EXP bonus is already active today.",409);}await t.CommitAsync(ct);var result=new BattleExpActivityView(activity.id,true,true,Condition(level),Percent(level),activity.end);await push.SendAsync(player,"activity.updated",new{kind="battleExp",result.AddPercent},ct);return result;}
 public async Task<double> MultiplierAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int level,CancellationToken ct){if(level<55)return 0;var activity=await ActiveAsync(c,t,ct);if(activity is null)return 0;await using var q=new NpgsqlCommand("SELECT 1 FROM player_battle_exp_activity WHERE player_id=$1 AND activity_id=$2 AND active_day=$3",c,t);q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(activity.Value.id);q.Parameters.AddWithValue(Day().ToDateTime(TimeOnly.MinValue));return await q.ExecuteScalarAsync(ct)is null?0:Percent(level)/100d;}
 static string Condition(int level)=>level<70?"55-69":level<80?"70-79":"80+";static int Percent(int level)=>level<55?0:level<70?10:level<80?20:30;
 static async Task<(long id,DateTimeOffset end)?> ActiveAsync(NpgsqlConnection c,NpgsqlTransaction? t,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT id,end_at FROM scheduled_activities WHERE activity_type=1 AND start_at<=now() AND end_at>=now() ORDER BY start_at DESC LIMIT 1",c,t);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?(r.GetInt64(0),r.GetFieldValue<DateTimeOffset>(1)):null;}
}
