using CTXD.Server.Data;
using CTXD.Server.Models;
using Npgsql;

namespace CTXD.Server.Services;

public sealed class CivilAffairService(GameDb db,CanonicalContent content,TechnologyEffectService technologies,ExperienceService experience)
{
    public async Task<CivilAffairsView> GetAsync(long playerId,int generalId,CancellationToken ct)
    {await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);var level=await CivilLevelAsync(c,t,playerId,generalId,ct);foreach(var affair in content.OfficerAffairs.Values.Where(x=>level>=x.OpenLevel)){var affairLevel=Math.Min(affair.MaxLevel,Math.Max(1,(level-affair.OpenLevel)/Math.Max(1,affair.UpgradeInterval)+1));await using var add=new NpgsqlCommand("INSERT INTO player_civil_affairs(player_id,general_id,affair_id,level) VALUES($1,$2,$3,$4) ON CONFLICT(player_id,general_id,affair_id) DO UPDATE SET level=GREATEST(player_civil_affairs.level,$4)",c,t);add.Parameters.AddWithValue(playerId);add.Parameters.AddWithValue(generalId);add.Parameters.AddWithValue(affair.Id);add.Parameters.AddWithValue(affairLevel);await add.ExecuteNonQueryAsync(ct);}var result=new List<CivilAffairView>();await using(var cmd=new NpgsqlCommand("SELECT affair_id,level,started_at FROM player_civil_affairs WHERE player_id=$1 AND general_id=$2 ORDER BY affair_id",c,t)){cmd.Parameters.AddWithValue(playerId);cmd.Parameters.AddWithValue(generalId);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var id=r.GetInt32(0);if(content.OfficerAffairs.TryGetValue(id,out var a))result.Add(new(id,a.Name,r.GetInt32(1),a.ResourceOutputType,a.ResourceOutput+(r.GetInt32(1)-1)*a.UpgradeOutputIncrease,a.Time,r.IsDBNull(2)?null:r.GetFieldValue<DateTimeOffset>(2)));}}await t.CommitAsync(ct);return new(generalId,result);}

    public async Task StartAsync(long playerId,int generalId,int affairId,CancellationToken ct)
    {await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);var level=await CivilLevelAsync(c,t,playerId,generalId,ct);if(!content.OfficerAffairs.TryGetValue(affairId,out var affair)||level<affair.OpenLevel)throw new GameException("AFFAIR_MISSING","Affair is not available.");var quality=content.Generals.TryGetValue(generalId,out var general)?general.Quality:0;await using(var count=new NpgsqlCommand("SELECT count(*) FROM player_civil_affairs WHERE player_id=$1 AND general_id=$2 AND started_at IS NOT NULL",c,t)){count.Parameters.AddWithValue(playerId);count.Parameters.AddWithValue(generalId);if(Convert.ToInt32(await count.ExecuteScalarAsync(ct))>=quality)throw new GameException("AFFAIR_LIMIT","This civil general has reached the running-affair limit.");}await using(var cmd=new NpgsqlCommand("UPDATE player_civil_affairs SET started_at=now() WHERE player_id=$1 AND general_id=$2 AND affair_id=$3 AND started_at IS NULL",c,t)){cmd.Parameters.AddWithValue(playerId);cmd.Parameters.AddWithValue(generalId);cmd.Parameters.AddWithValue(affairId);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new GameException("AFFAIR_RUNNING","Affair is already running or has not been initialized.");}await t.CommitAsync(ct);}

    public async Task<CivilAffairReward?> StopAsync(long playerId,int generalId,int affairId,CancellationToken ct)
    {await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await CivilLevelAsync(c,t,playerId,generalId,ct);if(!content.OfficerAffairs.TryGetValue(affairId,out var affair))throw new GameException("AFFAIR_MISSING","Affair does not exist.");int level;DateTimeOffset started;await using(var read=new NpgsqlCommand("SELECT level,started_at FROM player_civil_affairs WHERE player_id=$1 AND general_id=$2 AND affair_id=$3 FOR UPDATE",c,t)){read.Parameters.AddWithValue(playerId);read.Parameters.AddWithValue(generalId);read.Parameters.AddWithValue(affairId);await using var r=await read.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct)||r.IsDBNull(1))throw new GameException("AFFAIR_STOPPED","Affair is not running.");level=r.GetInt32(0);started=r.GetFieldValue<DateTimeOffset>(1);}var interval=TimeSpan.FromMinutes(affair.Time);var times=(int)((DateTimeOffset.UtcNow-started).Ticks/interval.Ticks);if(times<=0){await ClearAsync(c,t,playerId,generalId,affairId,null,ct);await t.CommitAsync(ct);return null;}var maxTimes=(int)(TimeSpan.FromDays(1).Ticks/(2*interval.Ticks));times=Math.Min(times,maxTimes);var next=times==maxTimes?(DateTimeOffset?)null:started+TimeSpan.FromTicks(interval.Ticks*times);var rate=1+await technologies.GetCompletedEffectAsync(playerId,5,0,ct,c,t)/100d;var amount=(int)Math.Round(times*(affair.ResourceOutput+(level-1)*affair.UpgradeOutputIncrease)*rate,MidpointRounding.AwayFromZero);if(content.Generals.TryGetValue(generalId,out var general)&&content.OfficerSpecialties.TryGetValue(general.TacticId,out var specialty)&&specialty.Type==affair.ResourceOutputType)amount=(int)(amount*specialty.Magnification);await AddRewardAsync(c,t,playerId,affair.ResourceOutputType,amount,ct);await AddCivilExpAsync(c,t,playerId,generalId,affair.OfficerExpOutput*times,ct);await ClearAsync(c,t,playerId,generalId,affairId,next,ct);await t.CommitAsync(ct);return new(affair.ResourceOutputType,amount);}

    static async Task<int> CivilLevelAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int general,CancellationToken ct){await using var cmd=new NpgsqlCommand("SELECT level FROM player_generals WHERE player_id=$1 AND general_id=$2 AND general_type=1 FOR UPDATE",c,t);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(general);var value=await cmd.ExecuteScalarAsync(ct);if(value is null)throw new GameException("CIVIL_GENERAL_MISSING","Civil general does not exist.");return Convert.ToInt32(value);}
    static async Task ClearAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int general,int affair,DateTimeOffset? next,CancellationToken ct){await using var cmd=new NpgsqlCommand("UPDATE player_civil_affairs SET started_at=$4 WHERE player_id=$1 AND general_id=$2 AND affair_id=$3",c,t);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(general);cmd.Parameters.AddWithValue(affair);cmd.Parameters.AddWithValue((object?)next??DBNull.Value);await cmd.ExecuteNonQueryAsync(ct);}
    async Task AddRewardAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int type,int amount,CancellationToken ct){if(amount<=0)return;if(type==5){await experience.AddAsync(c,t,player,amount,ct);return;}if(type==9){await using var gold=new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold+$2,updated_at=now() WHERE id=$1",c,t);gold.Parameters.AddWithValue(player);gold.Parameters.AddWithValue(amount);await gold.ExecuteNonQueryAsync(ct);return;}var column=type switch{1=>"copper",2=>"food",3=>"wood",4=>"iron",_=>throw new GameException("AFFAIR_REWARD_INVALID","Unknown affair reward type.",500)};await using var cmd=new NpgsqlCommand($"UPDATE player_resources SET {column}={column}+$2 WHERE player_id=$1",c,t);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(amount);await cmd.ExecuteNonQueryAsync(ct);}
    async Task AddCivilExpAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int general,int amount,CancellationToken ct){if(amount<=0||!content.Generals.TryGetValue(general,out var definition))return;int playerLv,level;long exp;await using(var cmd=new NpgsqlCommand("SELECT p.level,g.level,g.exp FROM players p JOIN player_generals g ON g.player_id=p.id AND g.general_id=$2 WHERE p.id=$1 FOR UPDATE OF p,g",c,t)){cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(general);await using var r=await cmd.ExecuteReaderAsync(ct);await r.ReadAsync(ct);playerLv=r.GetInt32(0);level=r.GetInt32(1);exp=r.GetInt64(2);}exp+=amount;while(level<playerLv){int need;try{need=content.Serial(definition.UpgradeExpSeriesId,level);}catch{break;}if(exp<need)break;exp-=need;level++;}await using var save=new NpgsqlCommand("UPDATE player_generals SET level=$3,exp=$4,updated_at=now() WHERE player_id=$1 AND general_id=$2",c,t);save.Parameters.AddWithValue(player);save.Parameters.AddWithValue(general);save.Parameters.AddWithValue(level);save.Parameters.AddWithValue(exp);await save.ExecuteNonQueryAsync(ct);}
}
