using CTXD.Server.Data;using Npgsql;
namespace CTXD.Server.Services;
public sealed record DailyGiftView(bool Available,DateTimeOffset ResetsAt);
public sealed record DailyGiftRequest(string RequestKey);
public sealed record DailyGiftReward(int ComboId,int[] Cards,int Gold,int Worship);
public sealed class DailyGiftService(GameDb db,GamePushHub push)
{
 static readonly (int id,double p,int[] cards,int gold,int worship)[] Rewards=
 [
  (1,.0333,[1,4,7],10,2),(2,.0499,[1,4,8],25,5),(3,.2262,[1,4,9],5,1),(4,.2595,[1,5,7],10,4),(5,.2761,[1,5,8],25,10),(6,.4524,[1,5,9],5,2),(7,.4857,[1,6,7],10,10),(8,.5023,[1,6,8],25,25),(9,.6786,[1,6,9],5,5),(10,.7286,[2,4,7],20,2),(11,.7319,[2,4,8],50,5),(12,.7652,[2,4,9],10,1),(13,.8152,[2,5,7],20,4),(14,.8185,[2,5,8],50,10),(15,.8518,[2,5,9],10,2),(16,.9018,[2,6,7],20,10),(17,.9051,[2,6,8],50,25),(18,.9384,[2,6,9],10,5),(19,.9417,[3,4,7],50,2),(20,.942,[3,4,8],125,5),(21,.9586,[3,4,9],25,1),(22,.9619,[3,5,7],50,4),(23,.9622,[3,5,8],125,10),(24,.9788,[3,5,9],25,2),(25,.9821,[3,6,7],50,10),(26,.9824,[3,6,8],125,25),(27,.999,[3,6,9],25,5)
 ];
 static readonly TimeSpan LegacyOffset=TimeSpan.FromHours(8);
 static DateOnly Day()=>DateOnly.FromDateTime(DateTimeOffset.UtcNow.ToOffset(LegacyOffset).Date);
 public async Task<DailyGiftView> GetAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await GateAsync(c,null,player,ct);await using var q=new NpgsqlCommand("SELECT 1 FROM player_daily_gift_claims WHERE player_id=$1 AND gift_day=$2",c);q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(Day().ToDateTime(TimeOnly.MinValue));var available=await q.ExecuteScalarAsync(ct)is null;var local=DateTimeOffset.UtcNow.ToOffset(LegacyOffset);var reset=new DateTimeOffset(local.Date.AddDays(1),LegacyOffset);return new(available,reset);}
 public async Task<DailyGiftReward> ClaimAsync(long player,string key,CancellationToken ct){if(string.IsNullOrWhiteSpace(key))throw new GameException("DAILY_GIFT_REQUEST_INVALID","Request key is required.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await GateAsync(c,t,player,ct);await using(var prior=new NpgsqlCommand("SELECT combo_id,cards,gold,worship FROM player_daily_gift_claims WHERE player_id=$1 AND request_key=$2",c,t)){prior.Parameters.AddWithValue(player);prior.Parameters.AddWithValue(key);await using var r=await prior.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){var old=new DailyGiftReward(r.GetInt32(0),r.GetFieldValue<int[]>(1),r.GetInt32(2),r.GetInt32(3));await t.CommitAsync(ct);return old;}}var roll=Random.Shared.NextDouble();var reward=Rewards.FirstOrDefault(x=>roll<=x.p);if(reward.id==0)reward=Rewards[^1];await using(var save=new NpgsqlCommand("INSERT INTO player_daily_gift_claims(player_id,gift_day,request_key,combo_id,gold,worship,cards) VALUES($1,$2,$3,$4,$5,$6,$7);UPDATE players SET sys_gold=sys_gold+$5 WHERE id=$1;UPDATE player_resources SET worship=worship+$6 WHERE player_id=$1",c,t)){save.Parameters.AddWithValue(player);save.Parameters.AddWithValue(Day().ToDateTime(TimeOnly.MinValue));save.Parameters.AddWithValue(key);save.Parameters.AddWithValue(reward.id);save.Parameters.AddWithValue(reward.gold);save.Parameters.AddWithValue(reward.worship);save.Parameters.AddWithValue(reward.cards);try{await save.ExecuteNonQueryAsync(ct);}catch(PostgresException e)when(e.SqlState==PostgresErrorCodes.UniqueViolation){throw new GameException("DAILY_GIFT_ALREADY_CLAIMED","Daily login gift was already claimed.",409);}}await t.CommitAsync(ct);var result=new DailyGiftReward(reward.id,reward.cards,reward.gold,reward.worship);await push.SendAsync(player,"activity.updated",new{kind="dailyGift",result.ComboId},ct);return result;}
 static async Task GateAsync(NpgsqlConnection c,NpgsqlTransaction? t,long player,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT 1 FROM player_functions WHERE player_id=$1 AND function_id=38",c,t);q.Parameters.AddWithValue(player);if(await q.ExecuteScalarAsync(ct)is null)throw new GameException("DAILY_GIFT_LOCKED","Legacy daily gift function 38 is not open.",403);}
}
