using CTXD.Server.Data;using Npgsql;
namespace CTXD.Server.Services;
public sealed record DragonActivityView(long ActivityId,bool Active,int Score,int Occupy,int Assist,int Cheer,int DragonNum,int[] Thresholds,int[] BoxRewards,DateTimeOffset EndsAt);
public sealed record DragonUseRequest(string RequestKey);
public sealed record DragonReward(int Type,int Num,int Quality,int Critical);
public sealed class DragonActivityService(GameDb db,ExperienceService experience,GamePushHub push,ISystemMailSender mail)
{
 static readonly (int score,int boxes)[] Tiers=[(5,8),(10,8),(30,9),(50,10),(70,11),(100,12),(130,14),(200,15)];
 static readonly (int type,int num,int quality,double weight)[] Rewards=[(1,750,3,.21),(1,1500,4,.27),(1,3000,5,.072),(1,7500,6,.048),(2,1,3,.0875),(2,2,4,.1125),(2,4,5,.03),(2,10,6,.02),(3,5,3,.035),(3,10,4,.045),(3,20,5,.012),(3,50,6,.008),(4,3000,3,.0175),(4,6000,4,.0225),(4,12000,5,.006),(4,30000,6,.004)];
 static readonly (int low,int high,int rate)[] LevelRates=[(0,50,2),(51,60,3),(61,70,5),(71,80,7),(81,90,8),(91,100,10),(101,999,12)];
 public async Task FinalizeAsync(long activityId,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);var rows=new List<(long player,int boxes)>();await using(var q=new NpgsqlCommand("SELECT player_id,dragon_num FROM player_dragon_activity WHERE activity_id=$1 AND dragon_num>0",c)){q.Parameters.AddWithValue(activityId);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))rows.Add((r.GetInt64(0),r.GetInt32(1)));}foreach(var row in rows){var total=new Dictionary<int,int>();for(var i=0;i<row.boxes;i++){var reward=await UseAsync(row.player,$"dragon-expiry:{activityId}:{i}",ct);total[reward.Type]=total.GetValueOrDefault(reward.Type)+reward.Num;}if(total.Count>0)await mail.SendAsync(row.player,"攻城活动",$"活动截止时，您还有{row.boxes}个宝箱未打开，系统自动领取，具体奖励如下："+string.Join("，",total.OrderBy(x=>x.Key).Select(x=>$"{x.Key}:{x.Value}")),[], $"dragon-expiry-mail:{activityId}",ct);}}
 public async Task<DragonActivityView> GetAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);var a=await CurrentAsync(c,null,player,ct)??throw new GameException("DRAGON_ACTIVITY_UNAVAILABLE","Dragon activity is unavailable.");int score=0,occupy=0,assist=0,cheer=0,boxes=0;await using(var q=new NpgsqlCommand("SELECT COALESCE(d.score,0),COALESCE(d.occupy_count,0),COALESCE(d.assist_count,0),COALESCE(d.cheer_count,0),COALESCE(d.dragon_num,0) FROM players p LEFT JOIN player_dragon_activity d ON d.player_id=p.id AND d.activity_id=$2 WHERE p.id=$1",c)){q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(a.id);await using var r=await q.ExecuteReaderAsync(ct);await r.ReadAsync(ct);score=r.GetInt32(0);occupy=r.GetInt32(1);assist=r.GetInt32(2);cheer=r.GetInt32(3);boxes=r.GetInt32(4);}return new(a.id,a.active,score,occupy,assist,cheer,boxes,Tiers.Select(x=>x.score).ToArray(),Tiers.Select(x=>x.boxes).ToArray(),a.end);}
 public async Task RecordScoreAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int kind,CancellationToken ct){var a=await ActiveAsync(c,t,ct);if(a is null)return;var amount=kind==1?5:kind==2?2:1;int before;await using(var q=new NpgsqlCommand("SELECT CASE WHEN activity_id=$2 THEN score ELSE 0 END FROM player_dragon_activity WHERE player_id=$1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(a.Value.id);before=Convert.ToInt32(await q.ExecuteScalarAsync(ct)??0);}var boxes=Tiers.Where(x=>x.score>before&&x.score<=before+amount).Sum(x=>x.boxes);await using var add=new NpgsqlCommand("INSERT INTO player_dragon_activity(player_id,activity_id,score,occupy_count,assist_count,cheer_count,dragon_num) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(player_id) DO UPDATE SET activity_id=$2,score=CASE WHEN player_dragon_activity.activity_id=$2 THEN player_dragon_activity.score+$3 ELSE $3 END,occupy_count=CASE WHEN player_dragon_activity.activity_id=$2 THEN player_dragon_activity.occupy_count+$4 ELSE $4 END,assist_count=CASE WHEN player_dragon_activity.activity_id=$2 THEN player_dragon_activity.assist_count+$5 ELSE $5 END,cheer_count=CASE WHEN player_dragon_activity.activity_id=$2 THEN player_dragon_activity.cheer_count+$6 ELSE $6 END,dragon_num=CASE WHEN player_dragon_activity.activity_id=$2 THEN player_dragon_activity.dragon_num+$7 ELSE $7 END",c,t);add.Parameters.AddWithValue(player);add.Parameters.AddWithValue(a.Value.id);add.Parameters.AddWithValue(amount);add.Parameters.AddWithValue(kind==1?1:0);add.Parameters.AddWithValue(kind==2?1:0);add.Parameters.AddWithValue(kind is not(1 or 2)?1:0);add.Parameters.AddWithValue(boxes);await add.ExecuteNonQueryAsync(ct);}
 public async Task<DragonReward> UseAsync(long player,string key,CancellationToken ct){if(string.IsNullOrWhiteSpace(key))throw new GameException("DRAGON_REQUEST_INVALID","Request key is required.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using(var old=new NpgsqlCommand("SELECT reward_type,reward_num,quality FROM player_dragon_rewards WHERE player_id=$1 AND request_key=$2",c,t)){old.Parameters.AddWithValue(player);old.Parameters.AddWithValue(key);await using var r=await old.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){var q=r.GetInt32(2);await t.CommitAsync(ct);return new(r.GetInt32(0),r.GetInt32(1),q,Critical(q));}}var a=await CurrentAsync(c,t,player,ct)??throw new GameException("DRAGON_ACTIVITY_UNAVAILABLE","Dragon activity is unavailable.");await using(var take=new NpgsqlCommand("UPDATE player_dragon_activity SET dragon_num=dragon_num-1 WHERE player_id=$1 AND activity_id=$2 AND dragon_num>0",c,t)){take.Parameters.AddWithValue(player);take.Parameters.AddWithValue(a.id);if(await take.ExecuteNonQueryAsync(ct)!=1)throw new GameException("DRAGON_BOX_EMPTY","No Dragon Boat box remains.");}var reward=Weighted();int level;await using(var p=new NpgsqlCommand("SELECT level FROM players WHERE id=$1",c,t)){p.Parameters.AddWithValue(player);level=Convert.ToInt32(await p.ExecuteScalarAsync(ct));}var num=reward.type is 1 or 4?reward.num*LevelRates.First(x=>level>=x.low&&level<=x.high).rate:reward.num;if(reward.type==1)await experience.AddAsync(c,t,player,num,ct);else if(reward.type==2){await using var q=new NpgsqlCommand("UPDATE players SET phantom_tokens=phantom_tokens+$2 WHERE id=$1",c,t);q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(num);await q.ExecuteNonQueryAsync(ct);}else if(reward.type==3){await using var q=new NpgsqlCommand("INSERT INTO player_quest_runtime(player_id,recruit_tokens) VALUES($1,$2) ON CONFLICT(player_id) DO UPDATE SET recruit_tokens=player_quest_runtime.recruit_tokens+$2,updated_at=now()",c,t);q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(num);await q.ExecuteNonQueryAsync(ct);}else{await using var q=new NpgsqlCommand("UPDATE player_resources SET food=food+$2 WHERE player_id=$1",c,t);q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(num);await q.ExecuteNonQueryAsync(ct);}await using(var ledger=new NpgsqlCommand("INSERT INTO player_dragon_rewards(player_id,request_key,reward_type,reward_num,quality) VALUES($1,$2,$3,$4,$5)",c,t)){ledger.Parameters.AddWithValue(player);ledger.Parameters.AddWithValue(key);ledger.Parameters.AddWithValue(reward.type);ledger.Parameters.AddWithValue(num);ledger.Parameters.AddWithValue(reward.quality);await ledger.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);var result=new DragonReward(reward.type,num,reward.quality,Critical(reward.quality));await push.SendAsync(player,"activity.updated",new{kind="dragon",result.Type,result.Num},ct);return result;}
 static int Critical(int q)=>q==4?2:q==5?4:q==6?10:0;static (int type,int num,int quality,double weight) Weighted(){var roll=Random.Shared.NextDouble();double sum=0;foreach(var r in Rewards){sum+=r.weight;if(roll<=sum)return r;}return Rewards[^1];}
 static async Task<(long id,bool active,DateTimeOffset end)?> CurrentAsync(NpgsqlConnection c,NpgsqlTransaction? t,long player,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT a.id,a.status=1,a.end_at FROM scheduled_activities a WHERE a.activity_type=4 AND (a.status=1 OR EXISTS(SELECT 1 FROM player_dragon_activity d WHERE d.player_id=$1 AND d.activity_id=a.id AND d.dragon_num>0)) ORDER BY a.start_at DESC LIMIT 1",c,t);q.Parameters.AddWithValue(player);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?(r.GetInt64(0),r.GetBoolean(1),r.GetFieldValue<DateTimeOffset>(2)):null;}static async Task<(long id,DateTimeOffset end)?> ActiveAsync(NpgsqlConnection c,NpgsqlTransaction t,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT id,end_at FROM scheduled_activities WHERE activity_type=4 AND status=1 AND start_at<=now() AND end_at>now() ORDER BY start_at DESC LIMIT 1",c,t);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?(r.GetInt64(0),r.GetFieldValue<DateTimeOffset>(1)):null;}
}
