using CTXD.Server.Data;using Npgsql;
namespace CTXD.Server.Services;
public sealed record LevelExpActivityView(long ActivityId,bool Active,bool RewardAvailable,double StartLevel,double CurrentLevel,double TargetLevel,int RewardExp,DateTimeOffset EndsAt);
public sealed record LevelExpActivityReward(int AddedExp);
public sealed class LevelExpActivityService(GameDb db,CanonicalContent content,ExperienceService experience,GamePushHub push)
{
 public async Task<LevelExpActivityView> GetAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);var schedule=await LatestAsync(c,t,ct)??throw new GameException("LEVEL_EXP_UNAVAILABLE","Legacy level EXP activity is unavailable.");int level;long exp;await using(var p=new NpgsqlCommand("SELECT level,exp FROM players WHERE id=$1 FOR UPDATE",c,t)){p.Parameters.AddWithValue(player);await using var r=await p.ExecuteReaderAsync(ct);await r.ReadAsync(ct);level=r.GetInt32(0);exp=r.GetInt64(1);}if(level<50)throw new GameException("LEVEL_EXP_LEVEL_LOW","Legacy level EXP activity opens at level 50.");int startLevel;long startExp;bool claimed;await using(var add=new NpgsqlCommand("INSERT INTO player_level_exp_activity(player_id,activity_id,start_level,start_exp) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING;SELECT start_level,start_exp,claimed FROM player_level_exp_activity WHERE player_id=$1 AND activity_id=$2 FOR UPDATE",c,t)){add.Parameters.AddWithValue(player);add.Parameters.AddWithValue(schedule.id);add.Parameters.AddWithValue(level>=60?level:60);add.Parameters.AddWithValue(level>=60?exp:0);await using var r=await add.ExecuteReaderAsync(ct);await r.NextResultAsync(ct);await r.ReadAsync(ct);startLevel=r.GetInt32(0);startExp=r.GetInt64(1);claimed=r.GetBoolean(2);}var start=Fraction(startLevel,startExp);var current=Fraction(level,exp);var tiers=Parse(schedule.param);var gained=current-start;var bonus=tiers.Where(x=>gained>=x.need).Select(x=>x.add).DefaultIfEmpty(0).Max();var reward=ToExperience(level,exp,bonus);var active=schedule.start<=DateTimeOffset.UtcNow&&schedule.end>=DateTimeOffset.UtcNow;await t.CommitAsync(ct);return new(schedule.id,active,!active&&!claimed,start,current,start+tiers.Max(x=>x.need),reward,schedule.end);}
 public async Task<LevelExpActivityReward> ClaimAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);var schedule=await LatestAsync(c,t,ct)??throw new GameException("LEVEL_EXP_UNAVAILABLE","Legacy level EXP activity is unavailable.");if(schedule.end>DateTimeOffset.UtcNow)throw new GameException("LEVEL_EXP_ACTIVE","Reward is calculated after the activity ends.");int level,startLevel;long exp,startExp;await using(var q=new NpgsqlCommand("SELECT p.level,p.exp,a.start_level,a.start_exp FROM player_level_exp_activity a JOIN players p ON p.id=a.player_id WHERE a.player_id=$1 AND a.activity_id=$2 AND a.claimed=false FOR UPDATE OF a,p",c,t)){q.Parameters.AddWithValue(player);q.Parameters.AddWithValue(schedule.id);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("LEVEL_EXP_REWARD_UNAVAILABLE","Reward missing or already claimed.");level=r.GetInt32(0);exp=r.GetInt64(1);startLevel=r.GetInt32(2);startExp=r.GetInt64(3);}var gained=Fraction(level,exp)-Fraction(startLevel,startExp);var bonus=Parse(schedule.param).Where(x=>gained>=x.need).Select(x=>x.add).DefaultIfEmpty(0).Max();var reward=ToExperience(level,exp,bonus);await using(var mark=new NpgsqlCommand("UPDATE player_level_exp_activity SET claimed=true,claimed_at=now() WHERE player_id=$1 AND activity_id=$2",c,t)){mark.Parameters.AddWithValue(player);mark.Parameters.AddWithValue(schedule.id);await mark.ExecuteNonQueryAsync(ct);}await experience.AddAsync(c,t,player,reward,ct);await t.CommitAsync(ct);await push.SendAsync(player,"activity.updated",new{kind="levelExp",reward},ct);return new(reward);}
 double Fraction(int level,long exp){int need;try{need=content.Serial(31,level);}catch{need=1;}return level+exp/(double)Math.Max(1,need);}int ToExperience(int level,long exp,double levels){var total=0;var point=exp/(double)Math.Max(1,content.Serial(31,level));if(point+levels>1){total+=(int)(content.Serial(31,level)*(1-point));levels=point+levels-1;level++;}else return(int)(content.Serial(31,level)*levels);while(levels>=1){total+=content.Serial(31,level++);levels--;}if(levels>0)total+=(int)(content.Serial(31,level)*levels);return total;}
 static (double need,double add)[] Parse(string raw)=>raw.Split(';',StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Split(',')).Where(x=>x.Length==2).Select(x=>(double.Parse(x[0],System.Globalization.CultureInfo.InvariantCulture),double.Parse(x[1],System.Globalization.CultureInfo.InvariantCulture))).ToArray();
 static async Task<(long id,DateTimeOffset start,DateTimeOffset end,string param)?> LatestAsync(NpgsqlConnection c,NpgsqlTransaction t,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT id,start_at,end_at,params_info FROM scheduled_activities WHERE activity_type=3 AND end_at>now()-interval '3 days' ORDER BY start_at DESC LIMIT 1",c,t);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?(r.GetInt64(0),r.GetFieldValue<DateTimeOffset>(1),r.GetFieldValue<DateTimeOffset>(2),r.GetString(3)):null;}
}
