using System.Text.Json;
using CTXD.Server.Data;
using Npgsql;

namespace CTXD.Server.Services;

public sealed record MailAttachment(string Kind,int Amount,int ItemId=0,int ItemType=0);
public sealed record PlayerMailRequest(string Recipient,string Title,string Body);
public sealed record MailView(long Id,string Sender,string Title,string Body,int Type,long LinkId,bool IsRead,bool IsDeleted,bool IsSaved,MailAttachment[] Attachments,bool AttachmentsClaimed,DateTimeOffset CreatedAt);
public sealed record MailPage(MailView[] Items,int Page,int TotalPages,int Unread);
public interface ISystemMailSender { Task<long> SendAsync(long playerId,string title,string body,IReadOnlyList<MailAttachment> attachments,string idempotencyKey,CancellationToken ct); }

public sealed class MailService(GameDb db,ExperienceService experience,IPlayerItemInventory items,GamePushHub push):ISystemMailSender
{
    const int PageSize=6;
    public async Task<MailPage> ListAsync(long player,int page,bool deleted,int? type,CancellationToken ct)
    {
        page=Math.Max(0,page);await using var c=await db.DataSource.OpenConnectionAsync(ct);var rows=new List<MailView>();
        await using(var cmd=new NpgsqlCommand(@"SELECT id,sender_name,title,body,mail_type,link_id,is_read,is_deleted,is_saved,attachments::text,attachments_claimed_at IS NOT NULL,created_at FROM player_mail WHERE recipient_player_id=$1 AND is_deleted=$2 AND ($3::smallint IS NULL OR mail_type=$3) ORDER BY created_at DESC LIMIT 6 OFFSET $4",c)){cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(deleted);cmd.Parameters.AddWithValue(type is null?DBNull.Value:(object)(short)type.Value);cmd.Parameters.AddWithValue(page*PageSize);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))rows.Add(Read(r));}
        long count;int unread;await using(var cmd=new NpgsqlCommand("SELECT count(*) FILTER(WHERE is_deleted=$2 AND ($3::smallint IS NULL OR mail_type=$3)),count(*) FILTER(WHERE NOT is_deleted AND NOT is_read) FROM player_mail WHERE recipient_player_id=$1",c)){cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(deleted);cmd.Parameters.AddWithValue(type is null?DBNull.Value:(object)(short)type.Value);await using var r=await cmd.ExecuteReaderAsync(ct);await r.ReadAsync(ct);count=r.GetInt64(0);unread=Convert.ToInt32(r.GetInt64(1));}
        return new(rows.ToArray(),page,(int)Math.Ceiling(count/(double)PageSize),unread);
    }
    public Task ReadAsync(long player,long mail,CancellationToken ct)=>SetAsync(player,mail,"is_read=true",false,ct);
    public Task DeleteAsync(long player,long mail,CancellationToken ct)=>SetAsync(player,mail,"is_deleted=true",false,ct);
    public Task RetrieveAsync(long player,long mail,CancellationToken ct)=>SetAsync(player,mail,"is_deleted=false",true,ct);
    public Task SaveAsync(long player,long mail,CancellationToken ct)=>SetAsync(player,mail,"is_saved=true,mail_type=3"," AND NOT is_deleted",ct);
    public async Task ThoroughDeleteAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand("DELETE FROM player_mail WHERE recipient_player_id=$1 AND is_deleted",c);cmd.Parameters.AddWithValue(player);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task<long> WriteAsync(long sender,string recipient,string title,string body,CancellationToken ct)
    {if(string.IsNullOrWhiteSpace(title)||string.IsNullOrWhiteSpace(body))throw new GameException("MAIL_CONTENT_REQUIRED","Mail title and body are required.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);long target;string senderName;short force,targetForce;await using(var cmd=new NpgsqlCommand("SELECT id,display_name,force_id FROM players WHERE id=$1",c,t)){cmd.Parameters.AddWithValue(sender);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("PLAYER_NOT_FOUND","Sender does not exist.",404);senderName=r.IsDBNull(1)?"":r.GetString(1);force=r.GetInt16(2);}await using(var cmd=new NpgsqlCommand("SELECT id,force_id FROM players WHERE display_name=$1",c,t)){cmd.Parameters.AddWithValue(recipient);await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("MAIL_RECIPIENT_NOT_FOUND","Recipient does not exist.",404);target=r.GetInt64(0);targetForce=r.GetInt16(1);}if(force!=targetForce)throw new GameException("MAIL_CROSS_FORCE_FORBIDDEN","Legacy mail cannot be sent to another nation.");long id;await using(var cmd=new NpgsqlCommand("INSERT INTO player_mail(sender_player_id,recipient_player_id,sender_name,title,body,mail_type) VALUES($1,$2,$3,$4,$5,1) RETURNING id",c,t)){cmd.Parameters.AddWithValue(sender);cmd.Parameters.AddWithValue(target);cmd.Parameters.AddWithValue(senderName);cmd.Parameters.AddWithValue(title);cmd.Parameters.AddWithValue(body);id=Convert.ToInt64(await cmd.ExecuteScalarAsync(ct));}await using(var trim=new NpgsqlCommand("DELETE FROM player_mail WHERE id IN(SELECT id FROM player_mail WHERE recipient_player_id=$1 AND NOT is_saved ORDER BY created_at DESC OFFSET 30)",c,t)){trim.Parameters.AddWithValue(target);await trim.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return id;}
    async Task SetAsync(long player,long mail,string set,bool requireDeleted,CancellationToken ct)=>await SetAsync(player,mail,set,requireDeleted?" AND is_deleted":"",ct);
    async Task SetAsync(long player,long mail,string set,string condition,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand($"UPDATE player_mail SET {set} WHERE id=$1 AND recipient_player_id=$2{condition}",c);cmd.Parameters.AddWithValue(mail);cmd.Parameters.AddWithValue(player);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new GameException("MAIL_NOT_FOUND","Mail does not exist for this player.",404);}
    public async Task<MailAttachment[]> ClaimAsync(long player,long mail,CancellationToken ct)
    {await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);string json;await using(var cmd=new NpgsqlCommand("SELECT attachments::text FROM player_mail WHERE id=$1 AND recipient_player_id=$2 AND NOT is_deleted AND attachments_claimed_at IS NULL FOR UPDATE",c,t)){cmd.Parameters.AddWithValue(mail);cmd.Parameters.AddWithValue(player);json=(string?)await cmd.ExecuteScalarAsync(ct)??throw new GameException("MAIL_ATTACHMENTS_UNAVAILABLE","Mail attachments are missing or already claimed.",409);}var rewards=JsonSerializer.Deserialize<MailAttachment[]>(json,new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??[];foreach(var reward in rewards)await GrantAsync(c,t,player,reward,ct);await using(var done=new NpgsqlCommand("UPDATE player_mail SET attachments_claimed_at=now(),is_read=true WHERE id=$1",c,t)){done.Parameters.AddWithValue(mail);await done.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return rewards;}
    async Task GrantAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,MailAttachment reward,CancellationToken ct){if(reward.Amount<=0)throw new GameException("MAIL_ATTACHMENT_INVALID","Invalid system-mail attachment.",500);if(reward.Kind.Equals("exp",StringComparison.OrdinalIgnoreCase)){await experience.AddAsync(c,t,player,reward.Amount,ct);return;}if(reward.Kind.Equals("item",StringComparison.OrdinalIgnoreCase)){await items.GrantAsync(c,t,player,reward.ItemId,reward.ItemType,reward.Amount,ct);return;}var column=reward.Kind.ToLowerInvariant() switch{"copper"=>"copper","wood"=>"wood","food"=>"food","iron"=>"iron",_=>throw new GameException("MAIL_ATTACHMENT_DEPENDENCY",$"Unsupported mail attachment: {reward.Kind}.",500)};await using var cmd=new NpgsqlCommand($"UPDATE player_resources SET {column}={column}+$2 WHERE player_id=$1",c,t);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(reward.Amount);await cmd.ExecuteNonQueryAsync(ct);}
    public async Task<long> SendAsync(long player,string title,string body,IReadOnlyList<MailAttachment> attachments,string idempotencyKey,CancellationToken ct)
    {await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using(var lockCmd=new NpgsqlCommand("SELECT id FROM players WHERE id=$1 FOR UPDATE",c,t)){lockCmd.Parameters.AddWithValue(player);if(await lockCmd.ExecuteScalarAsync(ct)is null)throw new GameException("PLAYER_NOT_FOUND","Player does not exist.",404);}var json=JsonSerializer.Serialize(attachments);long id;await using(var cmd=new NpgsqlCommand("INSERT INTO player_mail(recipient_player_id,title,body,mail_type,link_id,attachments,source_key) VALUES($1,$2,$3,1,hashtextextended($4,0),$5::jsonb,$4) ON CONFLICT(recipient_player_id,source_key) WHERE source_key IS NOT NULL DO UPDATE SET source_key=excluded.source_key RETURNING id",c,t)){cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(title);cmd.Parameters.AddWithValue(body);cmd.Parameters.AddWithValue(idempotencyKey);cmd.Parameters.AddWithValue(json);id=Convert.ToInt64(await cmd.ExecuteScalarAsync(ct));}await using(var trim=new NpgsqlCommand("DELETE FROM player_mail WHERE id IN(SELECT id FROM player_mail WHERE recipient_player_id=$1 AND NOT is_saved ORDER BY created_at DESC OFFSET 30)",c,t)){trim.Parameters.AddWithValue(player);await trim.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);await push.SendAsync(player,"mail.updated",new{id,newMail=true},ct);return id;}
    static MailView Read(NpgsqlDataReader r)=>new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetInt16(4),r.GetInt64(5),r.GetBoolean(6),r.GetBoolean(7),r.GetBoolean(8),JsonSerializer.Deserialize<MailAttachment[]>(r.GetString(9),new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??[],r.GetBoolean(10),r.GetFieldValue<DateTimeOffset>(11));
}
