using CTXD.Server.Data;
using CTXD.Server.Domain;
using Npgsql;

namespace CTXD.Server.Services;

public sealed record MarketOffer(int Slot, int ProductId, string ItemType, int ItemNum, string CostType, int CostNum, int Quality);
public sealed record MarketView(MarketOffer[] Offers, int CanBuy, DateTimeOffset RefreshAt);
public sealed record MarketBuyRequest(int Slot, string RequestKey);
public sealed record MarketBuyResult(string ItemType, int Added, int Remaining);
public sealed record BlackMarketView(int Spend, int Receive, DateTimeOffset CooldownUntil, int CooldownMaxMinutes);
public sealed record BlackMarketTradeRequest(int Left, int Right, string RequestKey);
public sealed record BlackMarketTradeResult(int Type, int Received, DateTimeOffset CooldownUntil);
public sealed record BlackMarketRecoverRequest(string RequestKey);
public sealed record BlackMarketRecoverResult(int Gold, DateTimeOffset CooldownUntil);
public sealed class MarketService(GameDb db, CanonicalContent content, TechnologyEffectService technologies,DstqActivityService dstq,IronActivityService ironActivity)
{
    public async Task<MarketView> GetAsync(long player, CancellationToken ct) { await using var c = await db.DataSource.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); var view = await EnsureAsync(c, t, player, ct); await t.CommitAsync(ct); return view; }
    public async Task<MarketBuyResult> BuyAsync(long player, int slot, string key, CancellationToken ct) { if (slot is < 1 or > 3 || string.IsNullOrWhiteSpace(key)) throw new GameException("MARKET_REQUEST_INVALID", "Market slot and request key are required."); await using var c = await db.DataSource.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await using (var prior = new NpgsqlCommand("SELECT item_type,item_num FROM player_market_purchases WHERE player_id=$1 AND request_key=$2", c, t)) { prior.Parameters.AddWithValue(player); prior.Parameters.AddWithValue(key); await using var r = await prior.ExecuteReaderAsync(ct); if (await r.ReadAsync(ct)) { var oldType = r.GetString(0); var oldNum = r.GetInt32(1); await t.CommitAsync(ct); return new(oldType, oldNum, -1); } } var view = await EnsureAsync(c, t, player, ct); if (view.CanBuy < 1) throw new GameException("MARKET_LIMIT_REACHED", "No market purchase attempts remain."); var offer = view.Offers.Single(x => x.Slot == slot); await DeductAsync(c, t, player, offer.CostType, offer.CostNum, ct); await GrantAsync(c, t, player, offer.ItemType, offer.ItemNum, ct); int level; await using (var lv = new NpgsqlCommand("SELECT level FROM players WHERE id=$1", c, t)) { lv.Parameters.AddWithValue(player); level = Convert.ToInt32(await lv.ExecuteScalarAsync(ct)); } var reroll = await RollAsync(c, t, player, level, ct); await using (var save = new NpgsqlCommand("UPDATE player_market SET can_buy=can_buy-1,offers=$8,refresh_at=now() WHERE player_id=$1;INSERT INTO player_market_purchases(player_id,request_key,product_id,item_type,item_num,cost_type,cost_num) VALUES($1,$2,$3,$4,$5,$6,$7);UPDATE player_quest_runtime SET market_buys=market_buys+1,updated_at=now() WHERE player_id=$1", c, t)) { save.Parameters.AddWithValue(player); save.Parameters.AddWithValue(key); save.Parameters.AddWithValue(offer.ProductId); save.Parameters.AddWithValue(offer.ItemType); save.Parameters.AddWithValue(offer.ItemNum); save.Parameters.AddWithValue(offer.CostType); save.Parameters.AddWithValue(offer.CostNum); save.Parameters.AddWithValue(reroll); await save.ExecuteNonQueryAsync(ct); } await t.CommitAsync(ct); return new(offer.ItemType, offer.ItemNum, view.CanBuy - 1); }
    async Task<MarketView> EnsureAsync(NpgsqlConnection c, NpgsqlTransaction t, long player, CancellationToken ct) { int level; await using (var open = new NpgsqlCommand("SELECT p.level FROM players p JOIN player_functions f ON f.player_id=p.id AND f.function_id=27 WHERE p.id=$1", c, t)) { open.Parameters.AddWithValue(player); var v = await open.ExecuteScalarAsync(ct); if (v is null) throw new GameException("MARKET_LOCKED", "Legacy market function 27 is not open.", 403); level = Convert.ToInt32(v); } decimal can = 10; int[] offers = []; DateTimeOffset refresh = DateTimeOffset.MinValue, accrued = DateTimeOffset.UtcNow; await using (var row = new NpgsqlCommand("INSERT INTO player_market(player_id) VALUES($1) ON CONFLICT DO NOTHING;SELECT can_buy,offers,refresh_at,buy_accrued_at FROM player_market WHERE player_id=$1 FOR UPDATE", c, t)) { row.Parameters.AddWithValue(player); await using var r = await row.ExecuteReaderAsync(ct); await r.NextResultAsync(ct); await r.ReadAsync(ct); can = r.GetDecimal(0); offers = r.GetFieldValue<int[]>(1); refresh = r.GetFieldValue<DateTimeOffset>(2); accrued = r.GetFieldValue<DateTimeOffset>(3); } var periods = Math.Max(0, (int)((DateTimeOffset.UtcNow - accrued).TotalMinutes / 30)); if (periods > 0) { var bonus = await technologies.GetCompletedEffectAsync(player, 2, 2, ct, c, t); can = Math.Min(24, can + periods * (decimal)(.5 + bonus)); accrued = accrued.AddMinutes(periods * 30); await using var gain = new NpgsqlCommand("UPDATE player_market SET can_buy=$2,buy_accrued_at=$3 WHERE player_id=$1", c, t); gain.Parameters.AddWithValue(player); gain.Parameters.AddWithValue(can); gain.Parameters.AddWithValue(accrued); await gain.ExecuteNonQueryAsync(ct); } var hour = new DateTimeOffset(DateTime.UtcNow.Year, DateTime.UtcNow.Month, DateTime.UtcNow.Day, DateTime.UtcNow.Hour, 0, 0, TimeSpan.Zero); if (offers.Length != 3 || refresh < hour) { offers = await RollAsync(c, t, player, level, ct); refresh = hour; await using var update = new NpgsqlCommand("UPDATE player_market SET offers=$2,refresh_at=$3 WHERE player_id=$1", c, t); update.Parameters.AddWithValue(player); update.Parameters.AddWithValue(offers); update.Parameters.AddWithValue(refresh); await update.ExecuteNonQueryAsync(ct); } var rate = 1 + await CityEffectAsync(c, t, player, 1, false, ct) / 100d; return new(offers.Select((id, i) => Offer(i + 1, id, rate)).ToArray(), (int)can, refresh.AddHours(1)); }
    public async Task<BlackMarketView> GetBlackAsync(long player, CancellationToken ct) { await using var c = await db.DataSource.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await RequireFunctionAsync(c, t, player, 43, ct); var tech = await technologies.GetCompletedIntEffectAsync(player, 37, 0, ct, c, t); var basis = Constant("BlackMarket.BaseQuantity"); var spend = (int)(basis * Constant("BlackMarket.BaseE") * (1 + tech / 100d)); var receive = (int)(basis * (1 + tech / 100d) * (1 + await CityEffectAsync(c, t, player, 2, true, ct) / 100d)); DateTimeOffset cd; await using (var q = new NpgsqlCommand("INSERT INTO player_black_market(player_id) VALUES($1) ON CONFLICT DO NOTHING;SELECT cooldown_until FROM player_black_market WHERE player_id=$1", c, t)) { q.Parameters.AddWithValue(player); await using var r = await q.ExecuteReaderAsync(ct); await r.NextResultAsync(ct); await r.ReadAsync(ct); cd = r.GetFieldValue<DateTimeOffset>(0); } await using (var visit = new NpgsqlCommand("UPDATE player_quest_runtime SET black_market_visits=black_market_visits+1,updated_at=now() WHERE player_id=$1", c, t)) { visit.Parameters.AddWithValue(player); await visit.ExecuteNonQueryAsync(ct); } await t.CommitAsync(ct); return new(spend, receive, cd, (int)Constant("BlackMarket.CDMax")); }
    public async Task<BlackMarketTradeResult> TradeBlackAsync(long player,int left,int right,string key,CancellationToken ct)
    {
        if(left is<1 or>3||right is<1 or>3||left==right||string.IsNullOrWhiteSpace(key))throw new GameException("BLACK_MARKET_REQUEST_INVALID","Invalid black-market trade.");
        await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await RequireFunctionAsync(c,t,player,43,ct);
        await using(var old=new NpgsqlCommand("SELECT right_type,received FROM player_black_market_trades WHERE player_id=$1 AND request_key=$2",c,t)){old.Parameters.AddWithValue(player);old.Parameters.AddWithValue(key);await using var r=await old.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){var rt=r.GetInt16(0);var amount=r.GetInt32(1);await t.CommitAsync(ct);return new(rt,amount,DateTimeOffset.MinValue);}}
        DateTimeOffset cooldown;await using(var q=new NpgsqlCommand("INSERT INTO player_black_market(player_id) VALUES($1) ON CONFLICT DO NOTHING;SELECT cooldown_until FROM player_black_market WHERE player_id=$1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(player);await using var r=await q.ExecuteReaderAsync(ct);await r.NextResultAsync(ct);await r.ReadAsync(ct);cooldown=r.GetFieldValue<DateTimeOffset>(0);}
        var max=TimeSpan.FromMinutes(Constant("BlackMarket.CDMax"));if(cooldown-DateTimeOffset.UtcNow>=max)throw new GameException("BLACK_MARKET_COOLDOWN","Black market cooldown reached its legacy cap.");
        var tech=await technologies.GetCompletedIntEffectAsync(player,37,0,ct,c,t);var basis=Constant("BlackMarket.BaseQuantity");var spent=(int)(basis*Constant("BlackMarket.BaseE")*(1+tech/100d));var baseReceived=(int)(basis*(1+tech/100d));var received=(int)(baseReceived*(1+await CityEffectAsync(c,t,player,2,true,ct)/100d));var cdMinutes=Math.Max(0,Constant("BlackMarket.BaseCD")-await CityEffectAsync(c,t,player,2,false,ct));
        var columns=new[]{"","copper","wood","food"};await using(var resource=new NpgsqlCommand($"UPDATE player_resources SET {columns[left]}={columns[left]}-$2,{columns[right]}={columns[right]}+$3 WHERE player_id=$1 AND {columns[left]}>=$2",c,t)){resource.Parameters.AddWithValue(player);resource.Parameters.AddWithValue(spent);resource.Parameters.AddWithValue(received);if(await resource.ExecuteNonQueryAsync(ct)!=1)throw new GameException("BLACK_MARKET_RESOURCE_NOT_ENOUGH","Not enough source resource.");}
        var next=(cooldown>DateTimeOffset.UtcNow?cooldown:DateTimeOffset.UtcNow).AddMinutes(cdMinutes);await using(var save=new NpgsqlCommand("UPDATE player_black_market SET cooldown_until=$3 WHERE player_id=$1;INSERT INTO player_black_market_trades(player_id,request_key,left_type,right_type,spent,received) VALUES($1,$2,$4,$5,$6,$7);UPDATE player_quest_runtime SET black_market_buys=black_market_buys+1,updated_at=now() WHERE player_id=$1",c,t)){save.Parameters.AddWithValue(player);save.Parameters.AddWithValue(key);save.Parameters.AddWithValue(next);save.Parameters.AddWithValue((short)left);save.Parameters.AddWithValue((short)right);save.Parameters.AddWithValue(spent);save.Parameters.AddWithValue(received);await save.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return new(right,received,next);
    }
    public async Task<BlackMarketRecoverResult> RecoverBlackAsync(long player,string key,CancellationToken ct)
    {
        if(string.IsNullOrWhiteSpace(key))throw new GameException("BLACK_MARKET_REQUEST_INVALID","Recovery request key is required.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await RequireFunctionAsync(c,t,player,43,ct);
        await using(var prior=new NpgsqlCommand("SELECT gold_spent FROM player_black_market_recoveries WHERE player_id=$1 AND request_key=$2",c,t)){prior.Parameters.AddWithValue(player);prior.Parameters.AddWithValue(key);var v=await prior.ExecuteScalarAsync(ct);if(v is not null){await t.CommitAsync(ct);return new(Convert.ToInt32(v),DateTimeOffset.UtcNow);}}
        DateTimeOffset until;await using(var q=new NpgsqlCommand("SELECT cooldown_until FROM player_black_market WHERE player_id=$1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(player);var v=await q.ExecuteScalarAsync(ct);if(v is null)throw new GameException("BLACK_MARKET_NOT_IN_COOLDOWN","Black market has no cooldown.");until=(DateTimeOffset)v;}var minutes=Math.Max(0,(until-DateTimeOffset.UtcNow).TotalMinutes);if(minutes<=0)throw new GameException("BLACK_MARKET_NOT_IN_COOLDOWN","Black market cooldown already ended.");var ci=content.ChargeItems[33];var cost=(int)Math.Ceiling(minutes/ci.Param)*ci.Cost;
        await using(var pay=new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold-$2 WHERE id=$1 AND sys_gold>=$2",c,t)){pay.Parameters.AddWithValue(player);pay.Parameters.AddWithValue(cost);if(await pay.ExecuteNonQueryAsync(ct)!=1)throw new GameException("MARKET_CURRENCY_NOT_ENOUGH","Not enough gold.");}
        await using(var clear=new NpgsqlCommand("UPDATE player_black_market SET cooldown_until=now() WHERE player_id=$1",c,t)){clear.Parameters.AddWithValue(player);await clear.ExecuteNonQueryAsync(ct);}await using(var ledger=new NpgsqlCommand("INSERT INTO player_black_market_recoveries(player_id,request_key,gold_spent) VALUES($1,$2,$3)",c,t)){ledger.Parameters.AddWithValue(player);ledger.Parameters.AddWithValue(key);ledger.Parameters.AddWithValue(cost);await ledger.ExecuteNonQueryAsync(ct);}await dstq.RecordGoldSpendAsync(c,t,player,cost,ct);await t.CommitAsync(ct);await dstq.PushAsync(player,ct);return new(cost,DateTimeOffset.UtcNow);
    }
    async Task<double> CityEffectAsync(NpgsqlConnection c, NpgsqlTransaction t, long player, int key, bool second, CancellationToken ct) { var defs = content.WorldCitySpecials.Where(x => x.Key == key && content.WorldCities.ContainsKey(x.CityId)).ToArray(); if (defs.Length == 0) return 0; await using var cmd = new NpgsqlCommand("SELECT force_id FROM players WHERE id=$1", c, t); cmd.Parameters.AddWithValue(player); var force = Convert.ToInt32(await cmd.ExecuteScalarAsync(ct)); await using var own = new NpgsqlCommand("SELECT city_id FROM world_cities WHERE owner_force_id=$1 AND city_id=ANY($2)", c, t); own.Parameters.AddWithValue(force); own.Parameters.AddWithValue(defs.Select(x => x.CityId).ToArray()); var id = await own.ExecuteScalarAsync(ct); if (id is null) return 0; var d = defs.First(x => x.CityId == Convert.ToInt32(id)); return second ? d.Parameter2 : d.Parameter1; }
    async Task RequireFunctionAsync(NpgsqlConnection c, NpgsqlTransaction t, long player, int function, CancellationToken ct) { await using var cmd = new NpgsqlCommand("SELECT 1 FROM player_functions WHERE player_id=$1 AND function_id=$2", c, t); cmd.Parameters.AddWithValue(player); cmd.Parameters.AddWithValue(function); if (await cmd.ExecuteScalarAsync(ct) is null) throw new GameException("MARKET_LOCKED", $"Legacy market function {function} is not open.", 403); }
    double Constant(string key) => content.Constants.TryGetValue(key, out var x) && double.TryParse(x.Value, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var v) ? v : throw new GameException("MARKET_STATIC_MISSING", $"Legacy constant {key} is missing.", 500);
    async Task<int[]> RollAsync(NpgsqlConnection c, NpgsqlTransaction t, long player, int level, CancellationToken ct) { var degree = content.MarketDegrees.FirstOrDefault(x => level >= x.MinLevel && level <= x.MaxLevel) ?? content.MarketDegrees.Last(); var pool = content.MarketProducts.Values.Where(x => x.Degree == degree.Degree).ToArray(); var result = new int[3]; for (var i = 0; i < 3; i++) result[i] = Weighted(pool, x => x.Prob).Id; if (await technologies.GetCompletedEffectAsync(player, 36, 0, ct, c, t) > 0 && Random.Shared.NextDouble() < degree.IronProbability) { var iron = content.MarketIron.Values.Where(x => x.Degree == degree.Degree).ToArray(); if (iron.Length > 0) result[Random.Shared.Next(3)] = 90000 + Weighted(iron, x => x.Prob).Id; } return result; }
    static T Weighted<T>(T[] pool, Func<T, double> weight) { var total = pool.Sum(x => Math.Max(0, weight(x))); var roll = Random.Shared.NextDouble() * total; foreach (var x in pool) { roll -= Math.Max(0, weight(x)); if (roll <= 0) return x; } return pool[^1]; }
    MarketOffer Offer(int slot, int id, double rate = 1) { if (id > 90000) { var x = content.MarketIron[id - 90000]; return new(slot, id, "iron", x.ItemNum, "copper", x.CostNum, x.Quality); } var p = content.MarketProducts[id]; var r = p.ItemType == "recruit_token" ? 1 : rate; return new(slot, id, p.ItemType, (int)(p.ItemNum * r), p.CostType, (int)(p.CostNum * r), p.Quality); }
    async Task DeductAsync(NpgsqlConnection c, NpgsqlTransaction t, long player, string type, int amount, CancellationToken ct) { if (type.Equals("gold", StringComparison.OrdinalIgnoreCase)) { await using var gold = new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold-$2 WHERE id=$1 AND sys_gold+$3>=$2", c, t); gold.Parameters.AddWithValue(player); gold.Parameters.AddWithValue(amount); gold.Parameters.AddWithValue(0); if (await gold.ExecuteNonQueryAsync(ct) != 1) throw new GameException("MARKET_CURRENCY_NOT_ENOUGH", "Not enough gold.");await dstq.RecordGoldSpendAsync(c,t,player,amount,ct); return; } var column = type.ToLowerInvariant() switch { "copper" => "copper", "lumber" => "wood", "food" => "food", "iron" => "iron", _ => throw new GameException("MARKET_CURRENCY_INVALID", "Unknown legacy market currency.", 500) }; await using var cmd = new NpgsqlCommand($"UPDATE player_resources SET {column}={column}-$2 WHERE player_id=$1 AND {column}>=$2", c, t); cmd.Parameters.AddWithValue(player); cmd.Parameters.AddWithValue(amount); if (await cmd.ExecuteNonQueryAsync(ct) != 1) throw new GameException("MARKET_CURRENCY_NOT_ENOUGH", "Not enough market currency."); }
    async Task GrantAsync(NpgsqlConnection c, NpgsqlTransaction t, long player, string type, int amount, CancellationToken ct) { if (type.Equals("gold", StringComparison.OrdinalIgnoreCase)) { await using var cmd = new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold+$2 WHERE id=$1", c, t); cmd.Parameters.AddWithValue(player); cmd.Parameters.AddWithValue(amount); await cmd.ExecuteNonQueryAsync(ct); return; } if (type.Equals("recruit_token", StringComparison.OrdinalIgnoreCase)) { await using var cmd = new NpgsqlCommand("UPDATE player_quest_runtime SET recruit_tokens=recruit_tokens+$2 WHERE player_id=$1", c, t); cmd.Parameters.AddWithValue(player); cmd.Parameters.AddWithValue(amount); await cmd.ExecuteNonQueryAsync(ct); return; } var column = type.ToLowerInvariant() switch { "copper" => "copper", "lumber" => "wood", "food" => "food", "iron" => "iron", _ => throw new GameException("MARKET_ITEM_INVALID", "Unknown legacy market product.", 500) }; await using var add = new NpgsqlCommand($"UPDATE player_resources SET {column}={column}+$2 WHERE player_id=$1", c, t); add.Parameters.AddWithValue(player); add.Parameters.AddWithValue(amount); await add.ExecuteNonQueryAsync(ct);if(column=="iron")await ironActivity.RecordGainAsync(c,t,player,amount,ct); }
}
