using System.Text.Json;
using System.Text.Json.Serialization;
using CTXD.Server.Data;
using Npgsql;

namespace CTXD.Server.Services;

public sealed record MineSlotView(int Id,int Type,string Name,int Position,string Pic,int Output,int Stone,string Operation,bool CanDo,bool Myself,long? OwnerPlayerId,int? OwnerForceId,string? OwnerName,int CurrentOutput,int CurrentStone,bool Double,long Cd);
public sealed record MineView(int Style,int CurrentPage,int TotalPage,bool HaveSmith,MineSlotView[] Mines);
public sealed record MineOccupyRequest(int MineId,int GeneralId);
public sealed record MineOccupyResult(int MineId,bool Captured,long? BattleId);
public sealed record MineRewardResult(int MineId,int Type,int Output,int Stone);

public sealed class MineService(GameDb db,CanonicalContent content,IPlayerItemInventory items,IronActivityService ironActivity,GamePushHub push)
{
    const int IronForceType=1,IronPersonalType=2,GemForceType=3,GemPersonalType=4;
    const int GemItemId=1,GemItemType=2,StoneItemId=1401,StoneItemType=16;
    static readonly TimeSpan RushWindow=TimeSpan.FromMinutes(15);

    sealed class MineDef
    {
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)] public int Id{get;set;}
        public string Name{get;set;}="";
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)] public int Type{get;set;}
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)] public int Page{get;set;}
        [JsonPropertyName("page_pos"),JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)] public int PagePosition{get;set;}
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)] public int Output{get;set;}
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)] public int Time{get;set;}
        public string Pic{get;set;}="";
        [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)] public int Stone{get;set;}
    }
    sealed record Holding(int MineId,int Type,long? Player,int? Force,int Mode,DateTimeOffset Started,DateTimeOffset? RushAt,DateTimeOffset? Ends,long[] Defenders);
    readonly IReadOnlyDictionary<int,MineDef> mines=Load<MineDef[]>(content.BaseDirectory,"mine.json").ToDictionary(x=>x.Id);

    public async Task<MineView> GetAsync(long playerId,int page,int style,CancellationToken ct)
    {
        var personalType=PersonalType(style);var forceType=ForceType(style);
        await TickDueAsync(ct);
        await using var c=await db.DataSource.OpenConnectionAsync(ct);
        int force;await using(var p=new NpgsqlCommand("SELECT force_id FROM players WHERE id=$1",c)){p.Parameters.AddWithValue(playerId);force=Convert.ToInt32(await p.ExecuteScalarAsync(ct)??throw new GameException("PLAYER_NOT_FOUND","Player does not exist.",404));}
        if(page==0){await using var own=new NpgsqlCommand("SELECT d.page FROM world_mine_holdings h JOIN (SELECT mine_id,page FROM jsonb_to_recordset($2::jsonb) AS x(mine_id int,page int)) d ON d.mine_id=h.mine_id WHERE h.owner_player_id=$1 AND h.mine_type=$3",c);own.Parameters.AddWithValue(playerId);own.Parameters.AddWithValue(JsonSerializer.Serialize(mines.Values.Select(x=>new{mine_id=x.Id,page=x.Page})));own.Parameters.AddWithValue(personalType);page=Convert.ToInt32(await own.ExecuteScalarAsync(ct)??1);}
        var total=mines.Values.Max(x=>x.Page);if(page<1||page>total)throw new GameException("MINE_PAGE_INVALID","Mine page is outside the legacy range.");
        var haveSmith=await HasSmith1Async(c,null,playerId,ct);
        var defs=mines.Values.Where(x=>(x.Type==personalType&&x.Page==page)||(x.Type==forceType&&x.Page==0)).OrderBy(x=>x.Type==forceType?1:0).ThenBy(x=>x.PagePosition).ToArray();
        var holdings=new Dictionary<int,Holding>();var ids=defs.Select(x=>x.Id).ToArray();
        await using(var q=new NpgsqlCommand("SELECT mine_id,mine_type,owner_player_id,owner_force_id,mode,started_at,rush_at,ends_at,defender_player_ids FROM world_mine_holdings WHERE mine_id=ANY($1)",c)){q.Parameters.AddWithValue(ids);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))holdings[r.GetInt32(0)]=ReadHolding(r);}
        var result=new List<MineSlotView>();foreach(var def in defs){holdings.TryGetValue(def.Id,out var h);string operation;bool can=true,myself=false;long? owner=null;int? ownerForce=null;string? ownerName=null;var output=0;var stone=0;var doubled=false;long cd=0;
            if(h is null)operation="occupy";
            else if(def.Type is IronForceType or GemForceType){ownerForce=h.Force;if(h.Force==force){operation="mine";await using var used=new NpgsqlCommand("SELECT 1 FROM player_force_mine_harvests WHERE player_id=$1 AND mine_type=$2 AND claimed_on=CURRENT_DATE",c);used.Parameters.AddWithValue(playerId);used.Parameters.AddWithValue(def.Type);can=await used.ExecuteScalarAsync(ct)is null;}else operation="occupy";}
            else{owner=h.Player;ownerForce=h.Force;myself=h.Player==playerId;if(owner.HasValue){await using var n=new NpgsqlCommand("SELECT name,force_id FROM players WHERE id=$1",c);n.Parameters.AddWithValue(owner.Value);await using var r=await n.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){ownerName=r.GetString(0);ownerForce=r.GetInt16(1);}}
                if(myself){(output,stone)=Output(def,h,DateTimeOffset.UtcNow);if(!haveSmith)stone=0;doubled=h.Mode==2;cd=Math.Max(0,(long)((h.Ends??DateTimeOffset.UtcNow)-DateTimeOffset.UtcNow).TotalMilliseconds);var elapsed=DateTimeOffset.UtcNow-h.Started;if(elapsed<RushWindow&&h.Mode==1)operation="rush";else{operation="abandon";can=elapsed>=RushWindow;}}
                else operation=ownerForce==force?"rob":"occupy";}
            result.Add(new(def.Id,def.Type,def.Name,def.PagePosition,def.Pic,def.Output,def.Stone,operation,can,myself,owner,ownerForce,ownerName,output,stone,doubled,cd));}
        return new(style,page,total,haveSmith,result.ToArray());
    }

    public async Task<MineOccupyResult> OccupyAsync(long playerId,int mineId,int generalId,CancellationToken ct)
    {
        if(!mines.TryGetValue(mineId,out var def))throw new GameException("MINE_NOT_FOUND","Mine does not exist.",404);
        await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);
        int force;await using(var p=new NpgsqlCommand("SELECT force_id FROM players WHERE id=$1 FOR UPDATE",c,t)){p.Parameters.AddWithValue(playerId);force=Convert.ToInt32(await p.ExecuteScalarAsync(ct)??throw new GameException("PLAYER_NOT_FOUND","Player does not exist.",404));}
        await using(var g=new NpgsqlCommand("SELECT 1 FROM player_generals WHERE player_id=$1 AND general_id=$2 AND general_type=2 AND state<=1 AND forces>0 FOR UPDATE",c,t)){g.Parameters.AddWithValue(playerId);g.Parameters.AddWithValue(generalId);if(await g.ExecuteScalarAsync(ct)is null)throw new GameException("MINE_GENERAL_INVALID","General cannot enter a Mine battle.");}
        if(def.Type is IronPersonalType or GemPersonalType)await using(var own=new NpgsqlCommand("SELECT 1 FROM world_mine_holdings WHERE owner_player_id=$1 AND mine_type=$2",c,t)){own.Parameters.AddWithValue(playerId);own.Parameters.AddWithValue(def.Type);if(await own.ExecuteScalarAsync(ct)is not null)throw new GameException("MINE_ALREADY_OWNED","Player already owns this kind of personal mine.");}
        Holding? holding=null;await using(var q=new NpgsqlCommand("SELECT mine_id,mine_type,owner_player_id,owner_force_id,mode,started_at,rush_at,ends_at,defender_player_ids FROM world_mine_holdings WHERE mine_id=$1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(mineId);await using var r=await q.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))holding=ReadHolding(r);}
        if(holding is not null&&((holding.Player==playerId)||(holding.Force==force&&def.Type is IronForceType or GemForceType)))throw new GameException("MINE_ALREADY_OWNED","Mine is already owned by the player or nation.");
        if(holding is null){await CaptureAsync(c,t,def,playerId,force,[],ct);await t.CommitAsync(ct);await push.BroadcastAsync("mine.updated",new{mineId},ct);return new(mineId,true,null);}
        await using(var active=new NpgsqlCommand("SELECT battle_id FROM world_mine_battles WHERE mine_id=$1 AND resolved_at IS NULL",c,t)){active.Parameters.AddWithValue(mineId);var existing=await active.ExecuteScalarAsync(ct);if(existing is not null){await t.CommitAsync(ct);return new(mineId,false,Convert.ToInt64(existing));}}
        var defenders=await DefenderGeneralsAsync(c,t,holding,def.Type,ct);if(defenders.Length==0){await CaptureAsync(c,t,def,playerId,force,[playerId],ct);await t.CommitAsync(ct);await push.BroadcastAsync("mine.updated",new{mineId},ct);return new(mineId,true,null);}
        var defenderPlayer=holding.Player??holding.Defenders.FirstOrDefault();if(defenderPlayer==0)defenderPlayer=(await FirstForcePlayerAsync(c,t,holding.Force!.Value,ct))??throw new GameException("MINE_DEFENDER_MISSING","Owned Mine has no eligible defender.",409);
        long battle;await using(var add=new NpgsqlCommand("INSERT INTO world_battle_handoffs(city_id,attacker_player_id,attacker_general_id,attacker_force_id,defender_force_id,battle_type,result_payload) VALUES($1,$2,$3,$4,$5,$6,jsonb_build_object('mineId',$1,'defenderPlayerId',$7,'defenderGenerals',to_jsonb($8::integer[]))) RETURNING id",c,t)){add.Parameters.AddWithValue(mineId);add.Parameters.AddWithValue(playerId);add.Parameters.AddWithValue(generalId);add.Parameters.AddWithValue(force);add.Parameters.AddWithValue(holding.Force??await PlayerForceAsync(c,t,holding.Player!.Value,ct));add.Parameters.AddWithValue(def.Type is IronPersonalType or GemPersonalType?6:7);add.Parameters.AddWithValue(defenderPlayer);add.Parameters.AddWithValue(defenders);battle=Convert.ToInt64(await add.ExecuteScalarAsync(ct));}
        await using(var link=new NpgsqlCommand("INSERT INTO world_mine_battles(battle_id,mine_id,expected_owner_player_id,expected_owner_force_id) VALUES($1,$2,$3,$4)",c,t)){link.Parameters.AddWithValue(battle);link.Parameters.AddWithValue(mineId);link.Parameters.AddWithValue((object?)holding.Player??DBNull.Value);link.Parameters.AddWithValue((object?)holding.Force??DBNull.Value);await link.ExecuteNonQueryAsync(ct);}
        await using(var state=new NpgsqlCommand("UPDATE player_generals SET state=3,updated_at=now() WHERE player_id=$1 AND general_id=$2",c,t)){state.Parameters.AddWithValue(playerId);state.Parameters.AddWithValue(generalId);await state.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return new(mineId,false,battle);
    }

    public async Task RushAsync(long playerId,int style,CancellationToken ct)
    {var type=PersonalType(style);await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("UPDATE world_mine_holdings SET mode=2,rush_at=now(),updated_at=now() WHERE owner_player_id=$1 AND mine_type=$2 AND mode=1 AND now()-started_at<=interval '15 minutes' RETURNING mine_id",c,t);q.Parameters.AddWithValue(playerId);q.Parameters.AddWithValue(type);if(await q.ExecuteScalarAsync(ct)is null)throw new GameException("MINE_RUSH_UNAVAILABLE","Mine is absent, already rushed, or its 15-minute rush window ended.");await t.CommitAsync(ct);await push.SendAsync(playerId,"mine.updated",new{style},ct);}

    public async Task<MineRewardResult> AbandonAsync(long playerId,int style,CancellationToken ct)
    {var type=PersonalType(style);MineRewardResult reward;await using(var c=await db.DataSource.OpenConnectionAsync(ct)){await using var t=await c.BeginTransactionAsync(ct);Holding h;await using(var q=new NpgsqlCommand("SELECT mine_id,mine_type,owner_player_id,owner_force_id,mode,started_at,rush_at,ends_at,defender_player_ids FROM world_mine_holdings WHERE owner_player_id=$1 AND mine_type=$2 FOR UPDATE",c,t)){q.Parameters.AddWithValue(playerId);q.Parameters.AddWithValue(type);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("MINE_NOT_OWNED","Player has no mine of this type.");h=ReadHolding(r);}if(DateTimeOffset.UtcNow-h.Started<RushWindow)throw new GameException("MINE_ABANDON_EARLY","Mine can be abandoned after 15 minutes.");reward=await SettleAndDeleteAsync(c,t,h,1,ct);await t.CommitAsync(ct);}await push.SendAsync(playerId,"mine.updated",reward,ct);return reward;}

    public async Task<MineRewardResult> HarvestForceAsync(long playerId,int style,CancellationToken ct)
    {var type=ForceType(style);var def=mines.Values.Single(x=>x.Type==type);await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);var force=await PlayerForceAsync(c,t,playerId,ct);await using(var own=new NpgsqlCommand("SELECT 1 FROM world_mine_holdings WHERE mine_id=$1 AND owner_force_id=$2",c,t)){own.Parameters.AddWithValue(def.Id);own.Parameters.AddWithValue(force);if(await own.ExecuteScalarAsync(ct)is null)throw new GameException("MINE_FORCE_NOT_OWNED","Player's nation does not own this Mine.");}await using(var claim=new NpgsqlCommand("INSERT INTO player_force_mine_harvests(player_id,mine_type,claimed_on,output) VALUES($1,$2,CURRENT_DATE,$3) ON CONFLICT DO NOTHING",c,t)){claim.Parameters.AddWithValue(playerId);claim.Parameters.AddWithValue(type);claim.Parameters.AddWithValue(def.Output);if(await claim.ExecuteNonQueryAsync(ct)!=1)throw new GameException("MINE_FORCE_ALREADY_HARVESTED","Force Mine was already harvested today.");}await GrantAsync(c,t,playerId,type,def.Output,0,ct);await t.CommitAsync(ct);return new(def.Id,type,def.Output,0);}

    public async Task ResolveBattleAsync(long battleId,bool attackerWon,CancellationToken ct)
    {int mineId;long attacker;int force;await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);long? expectedPlayer;int? expectedForce;await using(var q=new NpgsqlCommand("SELECT m.mine_id,m.expected_owner_player_id,m.expected_owner_force_id,h.attacker_player_id,h.attacker_force_id FROM world_mine_battles m JOIN world_battle_handoffs h ON h.id=m.battle_id WHERE m.battle_id=$1 AND m.resolved_at IS NULL FOR UPDATE OF m",c,t)){q.Parameters.AddWithValue(battleId);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct)){await t.CommitAsync(ct);return;}mineId=r.GetInt32(0);expectedPlayer=r.IsDBNull(1)?null:r.GetInt64(1);expectedForce=r.IsDBNull(2)?null:r.GetInt16(2);attacker=r.GetInt64(3);force=r.GetInt16(4);}if(attackerWon&&mines.TryGetValue(mineId,out var def)){await using var current=new NpgsqlCommand("SELECT 1 FROM world_mine_holdings WHERE mine_id=$1 AND owner_player_id IS NOT DISTINCT FROM $2 AND owner_force_id IS NOT DISTINCT FROM $3 FOR UPDATE",c,t);current.Parameters.AddWithValue(mineId);current.Parameters.AddWithValue((object?)expectedPlayer??DBNull.Value);current.Parameters.AddWithValue((object?)expectedForce??DBNull.Value);if(await current.ExecuteScalarAsync(ct)is not null)await CaptureAsync(c,t,def,attacker,force,[attacker],ct);}await using(var done=new NpgsqlCommand("UPDATE world_mine_battles SET resolved_at=now() WHERE battle_id=$1",c,t)){done.Parameters.AddWithValue(battleId);await done.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);await push.BroadcastAsync("mine.updated",new{mineId,battleId,attackerWon},ct);}

    public async Task<int[]> FindDueAsync(CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var q=new NpgsqlCommand("SELECT mine_id FROM world_mine_holdings WHERE ends_at<=now() ORDER BY ends_at LIMIT 50",c);await using var r=await q.ExecuteReaderAsync(ct);var ids=new List<int>();while(await r.ReadAsync(ct))ids.Add(r.GetInt32(0));return ids.ToArray();}
    public async Task TickDueAsync(CancellationToken ct){foreach(var id in await FindDueAsync(ct))await SettleDueAsync(id,ct);}
    public async Task SettleDueAsync(int mineId,CancellationToken ct){MineRewardResult? reward=null;long? player=null;await using(var c=await db.DataSource.OpenConnectionAsync(ct)){await using var t=await c.BeginTransactionAsync(ct);Holding? h=null;await using(var q=new NpgsqlCommand("SELECT mine_id,mine_type,owner_player_id,owner_force_id,mode,started_at,rush_at,ends_at,defender_player_ids FROM world_mine_holdings WHERE mine_id=$1 AND ends_at<=now() FOR UPDATE",c,t)){q.Parameters.AddWithValue(mineId);await using var r=await q.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))h=ReadHolding(r);}if(h is not null){player=h.Player;reward=await SettleAndDeleteAsync(c,t,h,1,ct);}await t.CommitAsync(ct);}if(player.HasValue&&reward is not null)await push.SendAsync(player.Value,"mine.updated",reward,ct);}

    async Task CaptureAsync(NpgsqlConnection c,NpgsqlTransaction t,MineDef def,long winner,int force,long[] defenders,CancellationToken ct)
    {Holding? old=null;await using(var q=new NpgsqlCommand("SELECT mine_id,mine_type,owner_player_id,owner_force_id,mode,started_at,rush_at,ends_at,defender_player_ids FROM world_mine_holdings WHERE mine_id=$1 FOR UPDATE",c,t)){q.Parameters.AddWithValue(def.Id);await using var r=await q.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))old=ReadHolding(r);}if(old?.Player is long loser){var (output,stone)=Output(def,old,DateTimeOffset.UtcNow);output/=2;stone/=2;var loserHasSmith=def.Type==IronPersonalType&&await HasSmith1Async(c,t,loser,ct);var winnerHasSmith=loserHasSmith&&await HasSmith1Async(c,t,winner,ct);await GrantAsync(c,t,loser,def.Type,output,loserHasSmith?stone:0,ct);await GrantAsync(c,t,winner,def.Type,output,winnerHasSmith?stone:0,ct);}await using(var del=new NpgsqlCommand("DELETE FROM world_mine_holdings WHERE mine_id=$1",c,t)){del.Parameters.AddWithValue(def.Id);await del.ExecuteNonQueryAsync(ct);}var personal=def.Type is IronPersonalType or GemPersonalType;var duration=TimeSpan.FromMinutes(def.Time);await using var add=new NpgsqlCommand("INSERT INTO world_mine_holdings(mine_id,mine_type,owner_player_id,owner_force_id,ends_at,defender_player_ids) VALUES($1,$2,$3,$4,$5,$6)",c,t);add.Parameters.AddWithValue(def.Id);add.Parameters.AddWithValue(def.Type);add.Parameters.AddWithValue(personal?winner:DBNull.Value);add.Parameters.AddWithValue(personal?DBNull.Value:force);add.Parameters.AddWithValue(personal?DateTimeOffset.UtcNow+duration:DBNull.Value);add.Parameters.AddWithValue(defenders.Length==0?[winner]:defenders.Distinct().Take(5).ToArray());await add.ExecuteNonQueryAsync(ct);}
    async Task<MineRewardResult> SettleAndDeleteAsync(NpgsqlConnection c,NpgsqlTransaction t,Holding h,int numerator,CancellationToken ct){var def=mines[h.MineId];var(output,stone)=Output(def,h,DateTimeOffset.UtcNow);output=output*numerator;stone=stone*numerator;if(h.Type!=IronPersonalType||!await HasSmith1Async(c,t,h.Player!.Value,ct))stone=0;await GrantAsync(c,t,h.Player.Value,h.Type,output,stone,ct);await using var d=new NpgsqlCommand("DELETE FROM world_mine_holdings WHERE mine_id=$1",c,t);d.Parameters.AddWithValue(h.MineId);await d.ExecuteNonQueryAsync(ct);return new(h.MineId,h.Type,output,stone);}
    async Task GrantAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int type,int output,int stone,CancellationToken ct){if(output>0&&type is IronForceType or IronPersonalType){await using var add=new NpgsqlCommand("UPDATE player_resources SET iron=iron+$2,update_time=now() WHERE player_id=$1",c,t);add.Parameters.AddWithValue(player);add.Parameters.AddWithValue(output);await add.ExecuteNonQueryAsync(ct);await ironActivity.RecordGainAsync(c,t,player,output,ct);}else if(output>0)await items.GrantAsync(c,t,player,GemItemId,GemItemType,output,ct);if(stone>0)await items.GrantAsync(c,t,player,StoneItemId,StoneItemType,stone,ct);}
    static (int output,int stone) Output(MineDef def,Holding h,DateTimeOffset now){var cap=h.Ends??now;var end=now<cap?now:cap;var totalMinutes=Math.Max(0,(long)(end-h.Started).TotalMinutes);long normal=totalMinutes,rushed=0;if(h.RushAt.HasValue){normal=Math.Max(0,(long)(h.RushAt.Value-h.Started).TotalMinutes);rushed=Math.Max(0,totalMinutes-normal);}var output=(int)(def.Output*(normal+2d*rushed)/60d);var stone=def.Type==IronPersonalType&&def.Time>0?(int)(def.Stone*Math.Min(totalMinutes,def.Time)/(double)def.Time):0;return(output,stone);}
    async Task<int[]> DefenderGeneralsAsync(NpgsqlConnection c,NpgsqlTransaction t,Holding h,int type,CancellationToken ct){long? player=h.Player??h.Defenders.FirstOrDefault();if(player==0)player=null;if(!player.HasValue&&h.Force.HasValue)player=await FirstForcePlayerAsync(c,t,h.Force.Value,ct);if(!player.HasValue)return[];var list=new List<int>();await using var q=new NpgsqlCommand("SELECT general_id FROM player_generals WHERE player_id=$1 AND general_type=2 ORDER BY general_id LIMIT $2",c,t);q.Parameters.AddWithValue(player.Value);q.Parameters.AddWithValue(type is IronForceType or GemForceType?5:100);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))list.Add(r.GetInt32(0));return list.ToArray();}
    static async Task<bool> HasSmith1Async(NpgsqlConnection c,NpgsqlTransaction? t,long player,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT 1 FROM player_blacksmiths WHERE player_id=$1 AND smith_id=1",c,t);q.Parameters.AddWithValue(player);return await q.ExecuteScalarAsync(ct)is not null;}
    static async Task<long?> FirstForcePlayerAsync(NpgsqlConnection c,NpgsqlTransaction t,int force,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT p.id FROM players p WHERE p.force_id=$1 AND EXISTS(SELECT 1 FROM player_generals g WHERE g.player_id=p.id AND g.general_type=2) ORDER BY p.id LIMIT 1",c,t);q.Parameters.AddWithValue(force);var x=await q.ExecuteScalarAsync(ct);return x is null?null:Convert.ToInt64(x);}
    static async Task<int> PlayerForceAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,CancellationToken ct){await using var q=new NpgsqlCommand("SELECT force_id FROM players WHERE id=$1",c,t);q.Parameters.AddWithValue(player);return Convert.ToInt32(await q.ExecuteScalarAsync(ct));}
    static Holding ReadHolding(NpgsqlDataReader r)=>new(r.GetInt32(0),r.GetInt16(1),r.IsDBNull(2)?null:r.GetInt64(2),r.IsDBNull(3)?null:r.GetInt16(3),r.GetInt16(4),r.GetFieldValue<DateTimeOffset>(5),r.IsDBNull(6)?null:r.GetFieldValue<DateTimeOffset>(6),r.IsDBNull(7)?null:r.GetFieldValue<DateTimeOffset>(7),(long[])r.GetValue(8));
    static int PersonalType(int style)=>style switch{1=>IronPersonalType,2=>GemPersonalType,_=>throw new GameException("MINE_STYLE_INVALID","Mine style must be 1 (iron) or 2 (gem).")};
    static int ForceType(int style)=>style switch{1=>IronForceType,2=>GemForceType,_=>throw new GameException("MINE_STYLE_INVALID","Mine style must be 1 (iron) or 2 (gem).")};
    static T Load<T>(string dir,string file){var opt=new JsonSerializerOptions{PropertyNameCaseInsensitive=true,NumberHandling=JsonNumberHandling.AllowReadingFromString};return JsonSerializer.Deserialize<T>(File.ReadAllText(Path.Combine(dir,file)),opt)??throw new InvalidOperationException($"Cannot load {file}.");}
}
