using CTXD.Server.Data;using Npgsql;
namespace CTXD.Server.Services;
public sealed record PayEntitlementRequest(string OrderId,long PlayerId,int Gold,int PayType,string Source);public sealed record PayEntitlementResult(string OrderId,long PlayerId,int Gold,int VipLevel,int TotalPayPoint,bool Duplicate);
public sealed class PayEntitlementService(GameDb db,GamePushHub push)
{
 static readonly (int level,int point)[] Thresholds=[(1,10),(2,300),(3,1000),(4,2000),(5,5000),(6,10000),(7,20000),(8,50000),(9,100000),(10,200000),(11,500000)];
 public async Task<PayEntitlementResult> ApplyAsync(PayEntitlementRequest request,CancellationToken ct){if(string.IsNullOrWhiteSpace(request.OrderId)||request.PlayerId<=0||request.Gold<=0||request.PayType is not(0 or 1)||string.IsNullOrWhiteSpace(request.Source))throw new GameException("PAY_ENTITLEMENT_INVALID","Invalid trusted pay entitlement.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using(var old=new NpgsqlCommand("SELECT player_id,gold FROM player_pay_entitlements WHERE order_id=$1",c,t)){old.Parameters.AddWithValue(request.OrderId);await using var r=await old.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){var priorPlayer=r.GetInt64(0);var priorGold=r.GetInt32(1);if(priorPlayer!=request.PlayerId||priorGold!=request.Gold)throw new GameException("PAY_ORDER_CONFLICT","Order id was already used for another entitlement.",409);await r.DisposeAsync();int points;await using(var p=new NpgsqlCommand("SELECT pay_point FROM player_vip_runtime WHERE player_id=$1",c,t)){p.Parameters.AddWithValue(request.PlayerId);points=Convert.ToInt32(await p.ExecuteScalarAsync(ct));}await t.CommitAsync(ct);return new(request.OrderId,request.PlayerId,priorGold,Level(points),points,true);}}await using(var ensure=new NpgsqlCommand("INSERT INTO player_vip_runtime(player_id) SELECT id FROM players WHERE id=$1 ON CONFLICT DO NOTHING",c,t)){ensure.Parameters.AddWithValue(request.PlayerId);await ensure.ExecuteNonQueryAsync(ct);}await using(var save=new NpgsqlCommand("INSERT INTO player_pay_entitlements(order_id,player_id,gold,pay_type,source) VALUES($1,$2,$3,$4,$5);UPDATE players SET user_gold=user_gold+CASE WHEN $4=0 THEN $3 ELSE 0 END,sys_gold=sys_gold+CASE WHEN $4=1 THEN $3 ELSE 0 END WHERE id=$2;UPDATE player_vip_runtime SET pay_point=pay_point+$3,updated_at=now() WHERE player_id=$2 RETURNING pay_point",c,t)){save.Parameters.AddWithValue(request.OrderId);save.Parameters.AddWithValue(request.PlayerId);save.Parameters.AddWithValue(request.Gold);save.Parameters.AddWithValue((short)request.PayType);save.Parameters.AddWithValue(request.Source);var points=Convert.ToInt32(await save.ExecuteScalarAsync(ct));var level=Level(points);await using var vip=new NpgsqlCommand("UPDATE players SET consume_level=GREATEST(consume_level,$2) WHERE id=$1",c,t);vip.Parameters.AddWithValue(request.PlayerId);vip.Parameters.AddWithValue(level);await vip.ExecuteNonQueryAsync(ct);await t.CommitAsync(ct);await push.SendAsync(request.PlayerId,"pay.updated",new{gold=request.Gold,vipLevel=level,payPoint=points},ct);return new(request.OrderId,request.PlayerId,request.Gold,level,points,false);}}
 static int Level(int points){var level=0;foreach(var x in Thresholds)if(points>=x.point)level=x.level;return level;}
}
