using CTXD.Server.Data;
using CTXD.Server.Models;
using Npgsql;

namespace CTXD.Server.Services;

public sealed class PoliticsService(GameDb db,CanonicalContent content,DstqActivityService dstq)
{
    public async Task<PoliticsView> GetAsync(long playerId,CancellationToken ct)
    {await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await EnsureAndAssignAsync(c,t,playerId,ct);int count,loyal;await using(var state=new NpgsqlCommand("SELECT event_count,people_loyal FROM player_politics WHERE player_id=$1",c,t)){state.Parameters.AddWithValue(playerId);await using var r=await state.ExecuteReaderAsync(ct);await r.ReadAsync(ct);count=r.GetInt32(0);loyal=r.GetInt32(1);}var events=new List<PoliticsEventView>();await using(var cmd=new NpgsqlCommand("SELECT building_id,politics_event_id FROM player_buildings WHERE player_id=$1 AND politics_event_id>0 ORDER BY building_id",c,t)){cmd.Parameters.AddWithValue(playerId);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var building=r.GetInt32(0);var id=r.GetInt32(1);if(content.PoliticsEvents.TryGetValue(id,out var e))events.Add(new(building,id,e.Name,e.Disc,e.Pic,e.Option1,e.Option2,e.Reward1,e.Reward2,e.Gold1,e.Gold2));}}await t.CommitAsync(ct);return new(count,loyal,events);}

    public async Task<PoliticsReward> ChooseAsync(long playerId,int buildingId,int option,CancellationToken ct)
    {
        if(option is not(1 or 2))throw new GameException("POLITICS_OPTION_INVALID","Option must be 1 or 2.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await EnsureAndAssignAsync(c,t,playerId,ct);
        int eventId;await using(var cmd=new NpgsqlCommand("SELECT politics_event_id FROM player_buildings WHERE player_id=$1 AND building_id=$2 FOR UPDATE",c,t)){cmd.Parameters.AddWithValue(playerId);cmd.Parameters.AddWithValue(buildingId);eventId=Convert.ToInt32(await cmd.ExecuteScalarAsync(ct));}if(eventId==0||!content.PoliticsEvents.TryGetValue(eventId,out var e))throw new GameException("POLITICS_EVENT_MISSING","Building has no politics event.");
        var gold=option==1?e.Gold1:e.Gold2;if(gold>0){await ConsumeGoldAsync(c,t,playerId,gold,ct);await dstq.RecordGoldSpendAsync(c,t,playerId,gold,ct);}var reward=Parse(option==1?e.Reward1:e.Reward2);await ApplyRewardAsync(c,t,playerId,reward.type,reward.value,ct);
        await using(var clear=new NpgsqlCommand("UPDATE player_buildings SET politics_event_id=0 WHERE player_id=$1 AND building_id=$2;UPDATE player_politics SET event_count=event_count-1 WHERE player_id=$1 AND event_count>0;INSERT INTO player_quest_runtime(player_id,daily_events) VALUES($1,1) ON CONFLICT(player_id) DO UPDATE SET daily_events=player_quest_runtime.daily_events+1,updated_at=now()",c,t)){clear.Parameters.AddWithValue(playerId);clear.Parameters.AddWithValue(buildingId);await clear.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);return new(reward.type,reward.value);
    }

    async Task EnsureAndAssignAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,CancellationToken ct)
    {await using(var add=new NpgsqlCommand("INSERT INTO player_politics(player_id) VALUES($1) ON CONFLICT DO NOTHING",c,t)){add.Parameters.AddWithValue(player);await add.ExecuteNonQueryAsync(ct);}int count;DateTimeOffset last;await using(var read=new NpgsqlCommand("SELECT event_count,last_event_at FROM player_politics WHERE player_id=$1 FOR UPDATE",c,t)){read.Parameters.AddWithValue(player);await using var r=await read.ExecuteReaderAsync(ct);await r.ReadAsync(ct);count=r.GetInt32(0);last=r.GetFieldValue<DateTimeOffset>(1);}var hours=Math.Min(24-count,(int)(DateTimeOffset.UtcNow-last).TotalHours);if(hours<=0)return;var free=new List<(int id,int area)>();await using(var cmd=new NpgsqlCommand("SELECT building_id FROM player_buildings WHERE player_id=$1 AND politics_event_id=0 ORDER BY building_id FOR UPDATE",c,t)){cmd.Parameters.AddWithValue(player);await using var r=await cmd.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var id=r.GetInt32(0);if(content.Buildings.TryGetValue(id,out var b))free.Add((id,b.AreaType));}}var assigned=0;foreach(var building in free.OrderBy(_=>Random.Shared.Next()).Take(hours)){var candidates=content.PoliticsEvents.Values.Where(x=>x.Type==building.area).ToArray();if(candidates.Length==0)continue;var chosen=candidates[Random.Shared.Next(candidates.Length)];await using var save=new NpgsqlCommand("UPDATE player_buildings SET politics_event_id=$3 WHERE player_id=$1 AND building_id=$2",c,t);save.Parameters.AddWithValue(player);save.Parameters.AddWithValue(building.id);save.Parameters.AddWithValue(chosen.Id);await save.ExecuteNonQueryAsync(ct);assigned++;}await using var state=new NpgsqlCommand("UPDATE player_politics SET event_count=LEAST(24,event_count+$2),last_event_at=last_event_at+($3 * interval '1 hour') WHERE player_id=$1",c,t);state.Parameters.AddWithValue(player);state.Parameters.AddWithValue(assigned);state.Parameters.AddWithValue(hours);await state.ExecuteNonQueryAsync(ct);}
    static (string type,int value) Parse(string raw){var p=raw.Split(',');if(p.Length!=2||!int.TryParse(p[1],out var value))throw new GameException("POLITICS_REWARD_INVALID","Politics reward data is invalid.",500);return(p[0],value);}
    static async Task ConsumeGoldAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,int amount,CancellationToken ct){await using var cmd=new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold-LEAST(sys_gold,$2),user_gold=user_gold-GREATEST(0,$2-sys_gold),updated_at=now() WHERE id=$1 AND sys_gold+user_gold >= $2",c,t);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(amount);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new GameException("GOLD_NOT_ENOUGH","Not enough gold.");}
    static async Task ApplyRewardAsync(NpgsqlConnection c,NpgsqlTransaction t,long player,string type,int value,CancellationToken ct){if(type=="people_loyal"){await using var loyal=new NpgsqlCommand("UPDATE player_politics SET people_loyal=LEAST(100,people_loyal+$2) WHERE player_id=$1",c,t);loyal.Parameters.AddWithValue(player);loyal.Parameters.AddWithValue(value);await loyal.ExecuteNonQueryAsync(ct);return;}var column=type switch{"copper"=>"copper","food"=>"food","lumber"=>"wood",_=>throw new GameException("POLITICS_REWARD_INVALID","Unknown politics reward.",500)};await using var cmd=new NpgsqlCommand($"UPDATE player_resources SET {column}={column}+$2 WHERE player_id=$1",c,t);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(value);await cmd.ExecuteNonQueryAsync(ct);}
}
