using CTXD.Server.Data;using Npgsql;
namespace CTXD.Server.Services;
public sealed record TeamCreateRequest(int TeamType);
public sealed record TeamJoinRequest(Guid TeamId,int[] GeneralIds);
public sealed record TeamDeployRequest(Guid TeamId,long BattleId,int CurNum,int TeamBattleType);
public sealed record TeamMemberView(long PlayerId,string Name,int GeneralId,string GeneralName,int Level,int Forces);
public sealed record TeamView(Guid Id,string Name,long OwnerPlayerId,int TeamType,int MaxGenerals,DateTimeOffset ExpiresAt,TeamMemberView[] Members,bool IsOwner,bool Inspired,double InspireEffect,bool Ordered);
public sealed record TeamCostView(Guid TeamId,int CurNum,int MaxNum,long TotalForces,bool Free,int DeployGold,bool Ordered,int InspireCost,double InspireEffect,int InspireExp);
public sealed class TeamService(GameDb db,CanonicalContent content,GamePushHub push,ExperienceService experience,TechnologyEffectService technologies,BattleService battles,DstqActivityService dstq)
{
 public async Task<TeamView[]> ListAsync(long player,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await CleanupAsync(c,ct);short force;await using(var p=new NpgsqlCommand("SELECT force_id FROM players WHERE id=$1",c)){p.Parameters.AddWithValue(player);force=Convert.ToInt16(await p.ExecuteScalarAsync(ct));}var ids=new List<Guid>();await using(var q=new NpgsqlCommand("SELECT id FROM social_teams WHERE force_id=$1 ORDER BY created_at",c)){q.Parameters.AddWithValue(force);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))ids.Add(r.GetGuid(0));}var result=new List<TeamView>();foreach(var id in ids)result.Add(await ReadAsync(c,null,id,player,ct));return result.ToArray();}
 public async Task<TeamView> CreateAsync(long player,int type,CancellationToken ct){if(type!=1)throw new GameException("TEAM_TYPE_INVALID","Legacy world_legion type does not exist.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);string name;short force;int free;await using(var p=new NpgsqlCommand("SELECT p.display_name,p.force_id,p.team_times FROM players p JOIN player_functions f ON f.player_id=p.id AND f.function_id=59 WHERE p.id=$1 FOR UPDATE OF p",c,t)){p.Parameters.AddWithValue(player);await using var r=await p.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("TEAM_LOCKED","Legacy team function 59 is not open.",403);name=(r.IsDBNull(0)?"":r.GetString(0))+" Team";force=r.GetInt16(1);free=r.GetInt32(2);}if(free<=0){await using var pay=new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold-30 WHERE id=$1 AND sys_gold>=30",c,t);pay.Parameters.AddWithValue(player);if(await pay.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_GOLD_NOT_ENOUGH","Creating this legacy team costs 30 gold.");await dstq.RecordGoldSpendAsync(c,t,player,30,ct);}var id=Guid.NewGuid();var expires=DateTimeOffset.UtcNow.AddHours(1);await using(var save=new NpgsqlCommand("INSERT INTO social_teams(id,owner_player_id,force_id,team_type,name,max_generals,expires_at) VALUES($1,$2,$3,1,$4,50,$5)",c,t)){save.Parameters.AddWithValue(id);save.Parameters.AddWithValue(player);save.Parameters.AddWithValue(force);save.Parameters.AddWithValue(name);save.Parameters.AddWithValue(expires);await save.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);await push.BroadcastAsync("team.updated",new{id,force},ct);await using var read=await db.DataSource.OpenConnectionAsync(ct);return await ReadAsync(read,null,id,player,ct);}
 public async Task<TeamView> JoinAsync(long player,Guid id,int[] generals,CancellationToken ct){generals=generals.Distinct().ToArray();if(generals.Length==0)throw new GameException("TEAM_GENERALS_REQUIRED","Select at least one general.");await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);int max,count;short force;await using(var team=new NpgsqlCommand("SELECT max_generals,force_id,(SELECT count(*) FROM social_team_generals WHERE team_id=$1) FROM social_teams WHERE id=$1 AND expires_at>now() FOR UPDATE",c,t)){team.Parameters.AddWithValue(id);await using var r=await team.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("TEAM_NOT_FOUND","Team does not exist or expired.",404);max=r.GetInt32(0);force=r.GetInt16(1);count=Convert.ToInt32(r.GetInt64(2));}if(count+generals.Length>max)throw new GameException("TEAM_FULL","Team general capacity is full.");await using(var validate=new NpgsqlCommand("SELECT count(*) FROM player_generals g JOIN players p ON p.id=g.player_id WHERE g.player_id=$1 AND g.general_id=ANY($2) AND g.general_type=2 AND g.state<=1 AND g.forces>0 AND p.force_id=$3",c,t)){validate.Parameters.AddWithValue(player);validate.Parameters.AddWithValue(generals);validate.Parameters.AddWithValue(force);if(Convert.ToInt32(await validate.ExecuteScalarAsync(ct))!=generals.Length)throw new GameException("TEAM_GENERAL_INVALID","General cannot join this team.");}foreach(var general in generals){await using var add=new NpgsqlCommand("INSERT INTO social_team_generals(team_id,player_id,general_id) VALUES($1,$2,$3)",c,t);add.Parameters.AddWithValue(id);add.Parameters.AddWithValue(player);add.Parameters.AddWithValue(general);await add.ExecuteNonQueryAsync(ct);}await t.CommitAsync(ct);await push.BroadcastAsync("team.updated",new{id,force},ct);await using var read=await db.DataSource.OpenConnectionAsync(ct);return await ReadAsync(read,null,id,player,ct);}
 public async Task LeaveAsync(long player,Guid id,int general,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand("DELETE FROM social_team_generals WHERE team_id=$1 AND player_id=$2 AND general_id=$3",c);cmd.Parameters.AddWithValue(id);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(general);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_MEMBER_NOT_FOUND","General is not in this team.",404);await push.BroadcastAsync("team.updated",new{id},ct);}
 public async Task KickAsync(long owner,Guid id,long player,int general,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand("DELETE FROM social_team_generals g USING social_teams t WHERE g.team_id=t.id AND t.id=$1 AND t.owner_player_id=$2 AND g.player_id=$3 AND g.general_id=$4",c);cmd.Parameters.AddWithValue(id);cmd.Parameters.AddWithValue(owner);cmd.Parameters.AddWithValue(player);cmd.Parameters.AddWithValue(general);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_KICK_FORBIDDEN","Only the team owner can remove this general.",403);await push.BroadcastAsync("team.updated",new{id},ct);}
 public async Task DismissAsync(long owner,Guid id,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var cmd=new NpgsqlCommand("DELETE FROM social_teams WHERE id=$1 AND owner_player_id=$2",c);cmd.Parameters.AddWithValue(id);cmd.Parameters.AddWithValue(owner);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_DISMISS_FORBIDDEN","Only the owner can dismiss this team.",403);await push.BroadcastAsync("team.updated",new{id},ct);}
 public async Task<TeamCostView> CostAsync(long owner,Guid id,CancellationToken ct){await using var c=await db.DataSource.OpenConnectionAsync(ct);return await CostAsync(c,null,owner,id,ct);}
 public async Task<TeamCostView> InspireAsync(long owner,Guid id,CancellationToken ct){var ci=content.ChargeItems[63];await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);await using(var pay=new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold-$2 WHERE id=$1 AND sys_gold>=$2",c,t)){pay.Parameters.AddWithValue(owner);pay.Parameters.AddWithValue(ci.Cost);if(await pay.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_GOLD_NOT_ENOUGH","Not enough gold to inspire.");}await using(var team=new NpgsqlCommand("UPDATE social_teams SET inspired=true,inspire_effect=$3 WHERE id=$1 AND owner_player_id=$2 AND inspired=false AND expires_at>now()",c,t)){team.Parameters.AddWithValue(id);team.Parameters.AddWithValue(owner);team.Parameters.AddWithValue((double)ci.Param);if(await team.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_INSPIRE_FORBIDDEN","Only the owner may inspire once on an active team.");}await dstq.RecordGoldSpendAsync(c,t,owner,ci.Cost,ct);await experience.AddAsync(c,t,owner,500*ci.Cost,ct);var view=await CostAsync(c,t,owner,id,ct);await t.CommitAsync(ct);await push.BroadcastAsync("team.updated",new{id},ct);return view;}
 public async Task<TeamCostView> OrderAsync(long owner,Guid id,CancellationToken ct)
 {
  var ci=content.ChargeItems[72];await using var c=await db.DataSource.OpenConnectionAsync(ct);await using var t=await c.BeginTransactionAsync(ct);
  await using(var gate=new NpgsqlCommand("SELECT 1 FROM social_teams WHERE id=$1 AND owner_player_id=$2 AND ordered=false AND expires_at>now() FOR UPDATE",c,t)){gate.Parameters.AddWithValue(id);gate.Parameters.AddWithValue(owner);if(await gate.ExecuteScalarAsync(ct)is null)throw new GameException("TEAM_ORDER_FORBIDDEN","Only the owner may order once on an active team.");}
  var raw=new List<(long player,int general,int level,int forces)>();
  await using(var q=new NpgsqlCommand("SELECT g.player_id,g.general_id,pg.level,pg.forces FROM social_team_generals g JOIN player_generals pg ON pg.player_id=g.player_id AND pg.general_id=g.general_id WHERE g.team_id=$1 FOR UPDATE OF pg",c,t)){q.Parameters.AddWithValue(id);await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))raw.Add((r.GetInt64(0),r.GetInt32(1),r.GetInt32(2),r.GetInt32(3)));}
  var rows=new List<(long player,int general,int forces,int max,double food)>();
  foreach(var x in raw){int hpBonus;await using(var eq=new NpgsqlCommand("SELECT COALESCE(sum(CASE WHEN goods_type NOT IN(1,2,3,4,10,14) THEN attribute ELSE 0 END),0) FROM player_equipment WHERE player_id=$1 AND owner_general_id=$2",c,t)){eq.Parameters.AddWithValue(x.player);eq.Parameters.AddWithValue(x.general);hpBonus=Convert.ToInt32(await eq.ExecuteScalarAsync(ct));}var techHp=await technologies.GetCompletedIntEffectAsync(x.player,30,2,ct,c,t);var columns=2+await technologies.GetCompletedIntEffectAsync(x.player,4,0,ct,c,t);var max=(1200+(x.level-1)*24+hpBonus+techHp)/3*Math.Max(1,columns)*3;max-=max%6;var troopId=content.Generals.TryGetValue(x.general,out var gd)?gd.TroopId:0;var food=content.TroopConscripts.TryGetValue(troopId,out var consume)?consume.Food:0;rows.Add((x.player,x.general,x.forces,max,food));}
  if(rows.Count==0)throw new GameException("TEAM_EMPTY","Team has no generals.");var total=rows.Sum(x=>(long)x.forces);var totalMax=rows.Sum(x=>(long)x.max);if(total>=totalMax)throw new GameException("TEAM_FORCES_FULL","All team generals already have full forces.");var cost=(int)Math.Ceiling((1-total/(double)totalMax)*ci.Cost*rows.Count);
  await using(var pay=new NpgsqlCommand("UPDATE players SET sys_gold=sys_gold-$2 WHERE id=$1 AND sys_gold>=$2",c,t)){pay.Parameters.AddWithValue(owner);pay.Parameters.AddWithValue(cost);if(await pay.ExecuteNonQueryAsync(ct)!=1)throw new GameException("TEAM_GOLD_NOT_ENOUGH","Not enough gold for team order.");}
  await dstq.RecordGoldSpendAsync(c,t,owner,cost,ct);
  foreach(var group in rows.Where(x=>x.max>x.forces).GroupBy(x=>x.player)){var need=(int)Math.Ceiling(group.Sum(x=>(x.max-x.forces)*x.food));await using var food=new NpgsqlCommand("UPDATE player_resources SET food=food-$2 WHERE player_id=$1 AND food>=$2",c,t);food.Parameters.AddWithValue(group.Key);food.Parameters.AddWithValue(need);if(await food.ExecuteNonQueryAsync(ct)!=1)continue;foreach(var x in group){await using var fill=new NpgsqlCommand("UPDATE player_generals SET forces=$3,updated_at=now() WHERE player_id=$1 AND general_id=$2",c,t);fill.Parameters.AddWithValue(x.player);fill.Parameters.AddWithValue(x.general);fill.Parameters.AddWithValue(x.max);await fill.ExecuteNonQueryAsync(ct);}}
  await using(var done=new NpgsqlCommand("UPDATE social_teams SET ordered=true WHERE id=$1",c,t)){done.Parameters.AddWithValue(id);await done.ExecuteNonQueryAsync(ct);}await experience.AddAsync(c,t,owner,(int)(ci.Param*cost),ct);var view=await CostAsync(c,t,owner,id,ct);await t.CommitAsync(ct);await push.BroadcastAsync("team.updated",new{id},ct);return view;
 }
 async Task<TeamCostView> CostAsync(NpgsqlConnection c,NpgsqlTransaction? t,long owner,Guid id,CancellationToken ct){int count,max,teamTimes;long forces;bool ordered;double effect;await using(var q=new NpgsqlCommand("SELECT count(g.*),t.max_generals,COALESCE(sum(pg.forces),0),t.ordered,t.inspire_effect,p.team_times FROM social_teams t JOIN players p ON p.id=t.owner_player_id LEFT JOIN social_team_generals g ON g.team_id=t.id LEFT JOIN player_generals pg ON pg.player_id=g.player_id AND pg.general_id=g.general_id WHERE t.id=$1 AND t.owner_player_id=$2 AND t.expires_at>now() GROUP BY t.max_generals,t.ordered,t.inspire_effect,p.team_times",c,t)){q.Parameters.AddWithValue(id);q.Parameters.AddWithValue(owner);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new GameException("TEAM_NOT_FOUND","Owned active team not found.",404);count=Convert.ToInt32(r.GetInt64(0));max=r.GetInt32(1);forces=r.GetInt64(2);ordered=r.GetBoolean(3);effect=r.GetDouble(4);teamTimes=r.GetInt32(5);}var ci=content.ChargeItems[63];return new(id,count,max,forces,teamTimes>0,teamTimes>0?0:count*3,ordered,ci.Cost,effect*100,500*ci.Cost);}
 public async Task<object> DeployAsync(long owner,TeamDeployRequest request,CancellationToken ct){var result=await battles.JoinTeamAsync(owner,request.BattleId,request.TeamId,request.CurNum,request.TeamBattleType,ct);await push.BroadcastAsync("team.updated",new{id=request.TeamId,reason="deployed"},ct);await push.BroadcastAsync("battle.updated",new{battleId=request.BattleId,reason="team.deployed",deployed=result.deployed},ct);return new{battleId=request.BattleId,deployed=result.deployed,battle=result.battle};}
 static async Task CleanupAsync(NpgsqlConnection c,CancellationToken ct){await using var cmd=new NpgsqlCommand("DELETE FROM social_teams WHERE expires_at<=now()",c);await cmd.ExecuteNonQueryAsync(ct);}
 async Task<TeamView> ReadAsync(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,long viewer,CancellationToken ct){long owner;int type,max;string name;DateTimeOffset expires;bool inspired,ordered;double effect;await using(var q=new NpgsqlCommand("SELECT owner_player_id,team_type,max_generals,name,expires_at,inspired,inspire_effect,ordered FROM social_teams WHERE id=$1",c,t)){q.Parameters.AddWithValue(id);await using var r=await q.ExecuteReaderAsync(ct);await r.ReadAsync(ct);owner=r.GetInt64(0);type=r.GetInt32(1);max=r.GetInt32(2);name=r.GetString(3);expires=r.GetFieldValue<DateTimeOffset>(4);inspired=r.GetBoolean(5);effect=r.GetDouble(6);ordered=r.GetBoolean(7);}var members=new List<TeamMemberView>();await using(var q=new NpgsqlCommand("SELECT g.player_id,p.display_name,g.general_id,COALESCE(d.name,''),pg.level,pg.forces FROM social_team_generals g JOIN players p ON p.id=g.player_id JOIN player_generals pg ON pg.player_id=g.player_id AND pg.general_id=g.general_id LEFT JOIN LATERAL(SELECT $2::text name)d ON true WHERE g.team_id=$1 ORDER BY g.joined_at",c,t)){q.Parameters.AddWithValue(id);q.Parameters.AddWithValue("");await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var gid=r.GetInt32(2);members.Add(new(r.GetInt64(0),r.IsDBNull(1)?"":r.GetString(1),gid,content.Generals.TryGetValue(gid,out var gd)?gd.Name:"",r.GetInt32(4),r.GetInt32(5)));}}return new(id,name,owner,type,max,expires,members.ToArray(),owner==viewer,inspired,effect,ordered);}
}
