BEGIN;
CREATE TABLE IF NOT EXISTS accounts(
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS sessions(
  token_hash BYTEA PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_sessions_account ON sessions(account_id);

CREATE TABLE IF NOT EXISTS players(
  id BIGSERIAL PRIMARY KEY,
  account_id BIGINT NOT NULL UNIQUE REFERENCES accounts(id) ON DELETE CASCADE,
  display_name VARCHAR(7) NULL UNIQUE,
  pic INTEGER NOT NULL DEFAULT 0,
  force_id SMALLINT NOT NULL DEFAULT 0 CHECK(force_id BETWEEN 0 AND 3),
  level INTEGER NOT NULL DEFAULT 1,
  exp BIGINT NOT NULL DEFAULT 0,
  current_task_id INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS player_resources(
  player_id BIGINT PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
  copper BIGINT NOT NULL DEFAULT 0,
  wood BIGINT NOT NULL DEFAULT 0,
  food BIGINT NOT NULL DEFAULT 0,
  iron BIGINT NOT NULL DEFAULT 0,
  update_time TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS player_buildings(
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  building_id INTEGER NOT NULL,
  level INTEGER NOT NULL DEFAULT 1,
  state SMALLINT NOT NULL DEFAULT 0,
  upgrade_complete_at TIMESTAMPTZ NULL,
  PRIMARY KEY(player_id, building_id)
);
CREATE TABLE IF NOT EXISTS player_functions(
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  function_id INTEGER NOT NULL,
  PRIMARY KEY(player_id,function_id)
);
COMMIT;
