BEGIN;
ALTER TABLE players ADD COLUMN IF NOT EXISTS construction_slots INTEGER NOT NULL DEFAULT 1;
ALTER TABLE players ADD COLUMN IF NOT EXISTS free_construction_num INTEGER NOT NULL DEFAULT 0;
COMMIT;
