BEGIN;
ALTER TABLE battle_units
  ADD COLUMN IF NOT EXISTS quality INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS tactic_id INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tactic_damage DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tactic_range INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tactic_used BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS strategy_id INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tactic_attack INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tactic_defense INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tech_tactic_attack INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tech_tactic_defense INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS selected_action SMALLINT NOT NULL DEFAULT 2;
CREATE TABLE IF NOT EXISTS battle_rewards(
  battle_id BIGINT NOT NULL REFERENCES battles(id) ON DELETE CASCADE,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  general_id INTEGER NOT NULL,
  copper BIGINT NOT NULL DEFAULT 0,
  player_exp BIGINT NOT NULL DEFAULT 0,
  general_exp BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY(battle_id,player_id,general_id)
);
COMMIT;
