BEGIN;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS trial_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS trial_general_kills INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS trial_won BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS trial_attempt_ids TEXT NOT NULL DEFAULT '1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18';
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS task_type SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS task_target BIGINT NOT NULL DEFAULT 0;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS task_progress BIGINT NOT NULL DEFAULT 0;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS task_ends_at TIMESTAMPTZ NULL;
ALTER TABLE nation_forces ADD COLUMN IF NOT EXISTS task_won BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE IF NOT EXISTS nation_trial_npcs(
 id BIGSERIAL PRIMARY KEY, force_id SMALLINT NOT NULL, trial_id INTEGER NOT NULL, stage SMALLINT NOT NULL,
 city_id INTEGER NOT NULL, army_id INTEGER NOT NULL, defeated BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS ix_nation_trial_npcs_city ON nation_trial_npcs(city_id,defeated);
CREATE TABLE IF NOT EXISTS nation_task_npcs(
 id BIGSERIAL PRIMARY KEY, force_id SMALLINT NOT NULL, city_id INTEGER NOT NULL, army_id INTEGER NOT NULL,
 hp_value INTEGER NOT NULL, defeated BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS ix_nation_task_npcs_city ON nation_task_npcs(city_id,defeated);
CREATE TABLE IF NOT EXISTS player_nation_ranks(
 player_id BIGINT PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE, force_id SMALLINT NOT NULL,
 trial_kills INTEGER NOT NULL DEFAULT 0, trial_received BOOLEAN NOT NULL DEFAULT TRUE,
 protect_kills INTEGER NOT NULL DEFAULT 0, protect_received BOOLEAN NOT NULL DEFAULT TRUE,
 task_score BIGINT NOT NULL DEFAULT 0, task_received BOOLEAN NOT NULL DEFAULT TRUE,
 invest_available_at TIMESTAMPTZ NULL
);
CREATE TABLE IF NOT EXISTS nation_protections(
 force_id SMALLINT PRIMARY KEY, attacking_force_id SMALLINT NOT NULL, city_id INTEGER NOT NULL,
 trial_id INTEGER NOT NULL, ends_at TIMESTAMPTZ NOT NULL, won BOOLEAN NULL
);
COMMIT;
