BEGIN;
CREATE TABLE IF NOT EXISTS player_quest_runtime(
  player_id BIGINT PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
  kidnapper SMALLINT NOT NULL DEFAULT 3 CHECK(kidnapper BETWEEN 0 AND 3),
  bandit SMALLINT NOT NULL DEFAULT 3 CHECK(bandit BETWEEN 0 AND 3),
  battle_wins INTEGER NOT NULL DEFAULT 0,
  world_moves INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO player_quest_runtime(player_id) SELECT id FROM players ON CONFLICT DO NOTHING;
COMMIT;
