BEGIN;
ALTER TABLE social_teams ADD COLUMN IF NOT EXISTS inspired BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE social_teams ADD COLUMN IF NOT EXISTS inspire_effect DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE social_teams ADD COLUMN IF NOT EXISTS ordered BOOLEAN NOT NULL DEFAULT FALSE;
COMMIT;
