BEGIN;
ALTER TABLE players ADD COLUMN IF NOT EXISTS team_times INTEGER NOT NULL DEFAULT 0 CHECK(team_times>=0);
ALTER TABLE player_quest_runtime ADD COLUMN IF NOT EXISTS team_deploys INTEGER NOT NULL DEFAULT 0;
COMMIT;
