BEGIN;
ALTER TABLE players ADD COLUMN IF NOT EXISTS phantom_tokens INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS player_dragon_activity(player_id BIGINT PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,activity_id BIGINT NOT NULL REFERENCES scheduled_activities(id) ON DELETE CASCADE,score INTEGER NOT NULL DEFAULT 0,occupy_count INTEGER NOT NULL DEFAULT 0,assist_count INTEGER NOT NULL DEFAULT 0,cheer_count INTEGER NOT NULL DEFAULT 0,dragon_num INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS player_dragon_rewards(player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,request_key TEXT NOT NULL,reward_type INTEGER NOT NULL,reward_num INTEGER NOT NULL,quality INTEGER NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(player_id,request_key));
COMMIT;
