BEGIN;
ALTER TABLE player_vip_runtime ADD COLUMN IF NOT EXISTS pay_point INTEGER NOT NULL DEFAULT 0 CHECK(pay_point>=0);
CREATE TABLE IF NOT EXISTS player_pay_entitlements(order_id TEXT PRIMARY KEY,player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,gold INTEGER NOT NULL CHECK(gold>0),pay_type SMALLINT NOT NULL CHECK(pay_type IN(0,1)),source TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
COMMIT;
