ALTER TABLE kfwd_schedules ADD COLUMN IF NOT EXISTS basic_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE kfwd_schedules ADD COLUMN IF NOT EXISTS win_coefficient INTEGER NOT NULL DEFAULT 0;
ALTER TABLE kfwd_rewards ADD COLUMN IF NOT EXISTS score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE kfwd_rewards ADD COLUMN IF NOT EXISTS win_res BIGINT NOT NULL DEFAULT 0;
