CREATE TABLE IF NOT EXISTS kfgz_seasons(
  id BIGSERIAL PRIMARY KEY,season_no INTEGER NOT NULL UNIQUE,state SMALLINT NOT NULL DEFAULT 0,
  opens_at TIMESTAMPTZ NOT NULL,first_battle_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS kfgz_signups(
  season_id BIGINT NOT NULL REFERENCES kfgz_seasons(id) ON DELETE CASCADE,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,competitor_id BIGSERIAL,
  force_id SMALLINT NOT NULL,general_ids INTEGER[] NOT NULL,version BIGINT NOT NULL DEFAULT 0,
  sys_gold BIGINT NOT NULL,copper BIGINT NOT NULL,wood BIGINT NOT NULL,food BIGINT NOT NULL,iron BIGINT NOT NULL,
  signed_at TIMESTAMPTZ NOT NULL DEFAULT now(),synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(season_id,player_id),UNIQUE(season_id,competitor_id));
