BEGIN;
CREATE TABLE IF NOT EXISTS player_tickets(
    player_id BIGINT PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
    tickets BIGINT NOT NULL DEFAULT 0 CHECK(tickets>=0),
    no_tips BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMIT;
